-- Migration 006: seed the directory (25 real organizations + one opportunity each).
-- Run AFTER migration 005. Idempotent: clears prior directory rows (owner_id is
-- null) and re-inserts. User-owned orgs (owner_id set) are never touched.

delete from public.organizations where owner_id is null;

insert into public.organizations
  (id, owner_id, name, description, website, logo_url, image_url, category, tags, remote, international,
   min_age, country, state, city, verified, counts_for_service_hours, commitment_type, featured)
values
  ('e5000000-0000-4000-8000-000000000001', null, 'American Red Cross', 'One of the most recognized humanitarian organizations in the country, responding to disasters big and small every single day.', 'https://www.redcross.org', 'https://www.google.com/s2/favicons?domain=www.redcross.org&sz=128', null, 'disaster', array['no experience needed', 'training provided'], false, false, 16, 'United States', null, null, true, true, 'both', true),
  ('e5000000-0000-4000-8000-000000000002', null, 'Feeding America', 'The largest hunger-relief organization in the United States, powering a network of more than 200 food banks and 60,000 pantries and meal programs.', 'https://www.feedingamerica.org', 'https://www.google.com/s2/favicons?domain=www.feedingamerica.org&sz=128', null, 'food', array['good for crews', 'counts for school hours'], false, false, 14, 'United States', null, null, true, true, 'both', true),
  ('e5000000-0000-4000-8000-000000000003', null, 'Habitat for Humanity', 'A global nonprofit that has helped more than 46 million people build or improve a place they can call home.', 'https://www.habitat.org', 'https://www.google.com/s2/favicons?domain=www.habitat.org&sz=128', null, 'community', array['good for crews', 'training provided'], false, true, 16, 'United States', null, null, true, true, 'both', true),
  ('e5000000-0000-4000-8000-000000000004', null, 'Zooniverse', 'The world largest platform for people-powered research, connecting volunteers with real scientists on hundreds of active projects.', 'https://www.zooniverse.org', 'https://www.google.com/s2/favicons?domain=www.zooniverse.org&sz=128', null, 'tech', array['no experience needed', 'one-time'], true, true, 0, 'Global', null, null, true, true, 'ongoing', true),
  ('e5000000-0000-4000-8000-000000000005', null, 'Smithsonian Transcription Center', 'The Smithsonian Institution digital volunteer program, opening up the world largest museum and research complex to everyone.', 'https://transcription.si.edu', 'https://www.google.com/s2/favicons?domain=transcription.si.edu&sz=128', null, 'art', array['no experience needed', 'one-time'], true, false, 13, 'United States', null, null, true, true, 'ongoing', true),
  ('e5000000-0000-4000-8000-000000000006', null, 'Meals on Wheels America', 'A network of more than 5,000 community programs delivering meals and companionship to homebound seniors nationwide.', 'https://www.mealsonwheelsamerica.org', 'https://www.google.com/s2/favicons?domain=www.mealsonwheelsamerica.org&sz=128', null, 'seniors', array['recurring'], false, false, 16, 'United States', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000007', null, 'Best Buddies International', 'A nonprofit dedicated to friendship, jobs, and leadership development for people with intellectual and developmental disabilities.', 'https://www.bestbuddies.org', 'https://www.google.com/s2/favicons?domain=www.bestbuddies.org&sz=128', null, 'community', array['no experience needed', 'recurring'], false, true, 12, 'United States', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000008', null, 'UPchieve', 'A free, on-demand online tutoring nonprofit built for low-income high school students who need academic support after hours.', 'https://upchieve.org', 'https://www.google.com/s2/favicons?domain=upchieve.org&sz=128', null, 'education', array['no experience needed', 'counts for school hours'], true, false, 14, 'United States', null, null, true, true, 'ongoing', true),
  ('e5000000-0000-4000-8000-000000000009', null, 'Learn To Be', 'A nonprofit providing free 1-on-1 online tutoring to underserved K-12 students across the country.', 'https://www.learntobe.org', 'https://www.google.com/s2/favicons?domain=www.learntobe.org&sz=128', null, 'education', array['recurring', 'counts for school hours'], true, false, 13, 'United States', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000010', null, 'Crisis Text Line', 'A free, confidential, 24/7 mental-health support line staffed by trained volunteer crisis counselors reaching people over text.', 'https://www.crisistextline.org', 'https://www.google.com/s2/favicons?domain=www.crisistextline.org&sz=128', null, 'medicine', array['training provided', 'recurring'], true, false, 18, 'United States', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000011', null, 'Be My Eyes', 'A free app that connects people who are blind or have low vision with sighted volunteers for visual help through live video.', 'https://www.bemyeyes.com', 'https://www.google.com/s2/favicons?domain=www.bemyeyes.com&sz=128', null, 'community', array['no experience needed', 'one-time'], true, true, 17, 'Global', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000012', null, 'Translators without Borders', 'Part of CLEAR Global, a nonprofit closing the language gap in humanitarian and crisis response worldwide.', 'https://translatorswithoutborders.org', 'https://www.google.com/s2/favicons?domain=translatorswithoutborders.org&sz=128', null, 'community', array['recurring'], true, true, 18, 'Global', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000013', null, 'UN Online Volunteering', 'The official United Nations platform connecting volunteers with nonprofits and UN agencies for remote work that advances global development.', 'https://www.onlinevolunteering.org', 'https://www.google.com/s2/favicons?domain=www.onlinevolunteering.org&sz=128', null, 'community', array['leadership role'], true, true, 18, 'Global', null, null, true, true, 'both', false),
  ('e5000000-0000-4000-8000-000000000014', null, 'The Trevor Project', 'The leading suicide-prevention and crisis-intervention organization for LGBTQ young people.', 'https://www.thetrevorproject.org', 'https://www.google.com/s2/favicons?domain=www.thetrevorproject.org&sz=128', null, 'medicine', array['training provided', 'recurring'], true, false, 18, 'United States', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000015', null, 'Ronald McDonald House Charities', 'A nonprofit that keeps families close to their sick children with a home away from home near hospitals worldwide.', 'https://www.rmhc.org', 'https://www.google.com/s2/favicons?domain=www.rmhc.org&sz=128', null, 'medicine', array['good for crews'], false, true, 14, 'United States', null, null, true, true, 'both', false),
  ('e5000000-0000-4000-8000-000000000016', null, 'Special Olympics', 'A global movement providing year-round sports training and competition for children and adults with intellectual disabilities.', 'https://www.specialolympics.org', 'https://www.google.com/s2/favicons?domain=www.specialolympics.org&sz=128', null, 'sports', array['good for crews'], false, true, 12, 'United States', null, null, true, true, 'both', false),
  ('e5000000-0000-4000-8000-000000000017', null, 'Humane Society of the United States', 'The largest animal-protection organization in the country, working to end cruelty to animals everywhere.', 'https://www.humanesociety.org', 'https://www.google.com/s2/favicons?domain=www.humanesociety.org&sz=128', null, 'animals', array['recurring'], false, false, 16, 'United States', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000018', null, 'National Park Service', 'The federal agency caring for more than 400 national parks, monuments, and historic sites across America.', 'https://www.nps.gov', 'https://www.google.com/s2/favicons?domain=www.nps.gov&sz=128', null, 'environment', array['outdoors', 'good for crews'], false, false, 16, 'United States', null, null, true, true, 'both', false),
  ('e5000000-0000-4000-8000-000000000019', null, 'Operation Gratitude', 'A nonprofit that has sent millions of care packages and letters to troops, veterans, and first responders.', 'https://www.operationgratitude.com', 'https://www.google.com/s2/favicons?domain=www.operationgratitude.com&sz=128', null, 'veterans', array['no experience needed', 'one-time'], true, false, 0, 'United States', null, null, true, true, 'one-time', false),
  ('e5000000-0000-4000-8000-000000000020', null, 'DoSomething.org', 'One of the largest nonprofits built specifically for young people and social change, with millions of members.', 'https://www.dosomething.org', 'https://www.google.com/s2/favicons?domain=www.dosomething.org&sz=128', null, 'community', array['no experience needed', 'counts for school hours'], true, false, 13, 'United States', null, null, true, true, 'both', false),
  ('e5000000-0000-4000-8000-000000000021', null, 'Girls on the Run', 'A physical-activity based youth development program that builds confidence in girls through the power of running.', 'https://www.girlsontherun.org', 'https://www.google.com/s2/favicons?domain=www.girlsontherun.org&sz=128', null, 'sports', array['recurring'], false, false, 14, 'United States', null, null, true, true, 'both', false),
  ('e5000000-0000-4000-8000-000000000022', null, 'iNaturalist', 'A joint initiative of the California Academy of Sciences and National Geographic and one of the most popular nature apps in the world.', 'https://www.inaturalist.org', 'https://www.google.com/s2/favicons?domain=www.inaturalist.org&sz=128', null, 'environment', array['no experience needed', 'outdoors'], true, true, 13, 'Global', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000023', null, 'Tarjimly', 'A nonprofit and app that connects bilingual volunteers with refugees, immigrants, and the aid workers helping them.', 'https://www.tarjimly.org', 'https://www.google.com/s2/favicons?domain=www.tarjimly.org&sz=128', null, 'community', array['recurring'], true, true, 16, 'Global', null, null, true, true, 'ongoing', false),
  ('e5000000-0000-4000-8000-000000000024', null, 'Atlanta Community Food Bank', 'A regional food bank sourcing and distributing food across 29 metro Atlanta and north Georgia counties.', 'https://www.acfb.org', 'https://www.google.com/s2/favicons?domain=www.acfb.org&sz=128', null, 'food', array['good for crews', 'counts for school hours'], false, false, 14, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('e5000000-0000-4000-8000-000000000025', null, 'LifeLine Animal Project', 'The nonprofit that runs metro Atlanta county animal shelters with a mission to end the killing of healthy and treatable pets.', 'https://lifelineanimal.org', 'https://www.google.com/s2/favicons?domain=lifelineanimal.org&sz=128', null, 'animals', array['recurring'], false, false, 13, 'United States', 'GA', 'Atlanta', true, true, 'ongoing', false);

insert into public.opportunities
  (id, org_id, title, category, description, tags, min_age, remote, is_online, is_ongoing,
   hours_estimate, signup_link, external_url, starts_at, city, state)
values
  ('e6000000-0000-4000-8000-000000000001', 'e5000000-0000-4000-8000-000000000001', 'Become a Red Cross Volunteer', 'disaster', 'Volunteers are the heart of the Red Cross - more than 90% of the workforce is unpaid. You can help families recover after home fires and natural disasters, support blood drives that keep hospitals stocked, teach preparedness in your community, or take on virtual roles like casework and social media from home. Full training is provided, so no experience is needed to start making a real difference.', array['no experience needed', 'training provided'], 16, false, false, true, '4+ hrs / shift', 'https://www.redcross.org/volunteer/become-a-volunteer.html', 'https://www.redcross.org/volunteer/become-a-volunteer.html', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000002', 'e5000000-0000-4000-8000-000000000002', 'Volunteer at a Local Food Bank', 'food', 'Hunger exists in every county in America, and food banks rely on volunteers to move millions of pounds of food each week. Through your nearest Feeding America member bank you can sort and box donated groceries, pack weekend meal kits for kids, staff mobile pantries, or help at distribution events. Shifts are flexible, welcoming to groups, and a great way to log service hours with friends.', array['good for crews', 'counts for school hours'], 14, false, false, true, '2-4 hrs / shift', 'https://www.feedingamerica.org/take-action/volunteer', 'https://www.feedingamerica.org/take-action/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000003', 'e5000000-0000-4000-8000-000000000003', 'Build Homes with Habitat', 'community', 'Habitat brings volunteers and future homeowners together to build affordable housing side by side. On a local build site you might frame walls, paint, or landscape, and no construction experience is required because team leaders teach you everything on site. If swinging a hammer is not your thing, Habitat ReStore resale shops also need help sorting and selling donated goods to fund the mission.', array['good for crews', 'training provided'], 16, false, false, true, 'Full day', 'https://www.habitat.org/volunteer', 'https://www.habitat.org/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000004', 'e5000000-0000-4000-8000-000000000004', 'Power Real Research Online', 'tech', 'Zooniverse lets anyone contribute to genuine scientific discovery from a laptop or phone. You might classify distant galaxies, identify animals in trail-camera photos, or transcribe historic weather logs and letters, and your work goes directly to researchers who publish real findings. There is no minimum time commitment, tasks take just minutes each, and projects publish guidance for younger volunteers.', array['no experience needed', 'one-time'], 0, true, true, true, 'Flexible', 'https://www.zooniverse.org/projects', 'https://www.zooniverse.org/projects', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000005', 'e5000000-0000-4000-8000-000000000005', 'Transcribe Smithsonian Records', 'art', 'Behind the Smithsonian are millions of handwritten documents, field notes, diaries, and specimen labels that computers cannot read. As a digital volunteer you turn those images into searchable, accessible text that researchers and the public can use. Work as little or as much as you like from home, pick projects that match your interests from science to history to art, and see your contributions become part of the permanent record.', array['no experience needed', 'one-time'], 13, true, true, true, 'Flexible', 'https://transcription.si.edu', 'https://transcription.si.edu', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000006', 'e5000000-0000-4000-8000-000000000006', 'Deliver Meals to Seniors', 'seniors', 'For many homebound older adults, a Meals on Wheels volunteer is the only person they see all day. Volunteers deliver hot meals along a local route and take a moment to check in, share a smile, and make sure their neighbor is safe and well. Routes usually take an hour or two, fit around a normal schedule, and the friendly visit means as much as the food.', array['recurring'], 16, false, false, true, '1-2 hrs / route', 'https://www.mealsonwheelsamerica.org/volunteer', 'https://www.mealsonwheelsamerica.org/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000007', 'e5000000-0000-4000-8000-000000000007', 'Be a Buddy', 'community', 'Best Buddies pairs volunteers in one-to-one friendships with people who have intellectual and developmental disabilities, and runs school and college chapters across the country. As a buddy you hang out, text, and share activities with your match, building a real friendship that changes both of your lives. Chapters welcome middle and high schoolers, and the e-Buddies program offers an online pen-pal option too.', array['no experience needed', 'recurring'], 12, false, false, true, '1-2 hrs / week', 'https://www.bestbuddies.org/get-involved/volunteer/', 'https://www.bestbuddies.org/get-involved/volunteer/', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000008', 'e5000000-0000-4000-8000-000000000008', 'Tutor Students Online', 'education', 'UPchieve connects you with students who often do not have access to private tutoring, right when they are stuck on homework. You get a text notification when a student requests help, hop into a virtual classroom, and work through math, science, or writing one on one, or help with college and financial-aid questions. You set your own availability, there is no minimum commitment, and your hours are tracked so they can count toward service requirements.', array['no experience needed', 'counts for school hours'], 14, true, true, true, 'Flexible', 'https://app.upchieve.org/sign-up/volunteer/account', 'https://app.upchieve.org/sign-up/volunteer/account', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000009', 'e5000000-0000-4000-8000-000000000009', 'Tutor a K-12 Student', 'education', 'Learn To Be matches you with a student who needs steady support in a subject you know well, then gives you the tools and training to help them week after week. Sessions happen in an online classroom on a schedule you set with your student, and consistency is what makes the difference. It is a rewarding way to build a mentoring relationship and rack up meaningful, verifiable service hours.', array['recurring', 'counts for school hours'], 13, true, true, true, '1 hr / week', 'https://www.learntobe.org/volunteers', 'https://www.learntobe.org/volunteers', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000010', 'e5000000-0000-4000-8000-000000000010', 'Train as a Crisis Counselor', 'medicine', 'Crisis Text Line volunteers support people through anxiety, depression, self-harm, and moments of real crisis, all over text message. You receive around 30 hours of world-class training before ever taking a conversation, and a supervisor backs you up on every shift. This is a serious commitment of roughly 4 hours a week, and it is one of the most meaningful ways to help that exists.', array['training provided', 'recurring'], 18, true, true, true, '4 hrs / week', 'https://www.crisistextline.org/become-a-volunteer/', 'https://www.crisistextline.org/become-a-volunteer/', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000011', 'e5000000-0000-4000-8000-000000000011', 'Lend Your Eyes', 'community', 'When someone who is blind or low-vision needs a quick pair of eyes, Be My Eyes rings available volunteers around the world, and whoever answers first hops on a short video call. You might read a food label, check an expiration date, describe a photo, or help someone find something they dropped. Calls take just a few minutes, come only when you are free, and millions of volunteers already share the load.', array['no experience needed', 'one-time'], 17, true, true, true, 'A few min', 'https://www.bemyeyes.com/become-a-volunteer', 'https://www.bemyeyes.com/become-a-volunteer', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000012', 'e5000000-0000-4000-8000-000000000012', 'Translate for Humanitarian Aid', 'community', 'When disasters and health crises strike, information has to reach people in a language they actually understand, and that is where this community of volunteer linguists comes in. If you are fluent in more than one language you can translate health guidance, crisis alerts, and education materials for relief organizations operating in over 200 languages. Work is remote and flexible, and every translation can genuinely help keep people safe.', array['recurring'], 18, true, true, true, 'Flexible', 'https://translatorswithoutborders.org/volunteer/', 'https://translatorswithoutborders.org/volunteer/', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000013', 'e5000000-0000-4000-8000-000000000013', 'Volunteer Online for the UN', 'community', 'Through the UN Online Volunteering service you can support development organizations anywhere in the world without leaving home. Assignments range from writing and research to graphic design, translation, data analysis, and mentoring, and they plug directly into projects working on poverty, health, education, and human rights. It is a standout way for college-age volunteers to gain real experience while contributing to the UN Sustainable Development Goals.', array['leadership role'], 18, true, true, true, 'Flexible', 'https://www.onlinevolunteering.org', 'https://www.onlinevolunteering.org', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000014', 'e5000000-0000-4000-8000-000000000014', 'Support LGBTQ Youth', 'medicine', 'The Trevor Project provides 24/7 crisis support to LGBTQ young people who may have nowhere else to turn. As a trained digital crisis counselor you support youth over chat and text, and the organization provides thorough training and ongoing supervision before and during your shifts. It is a serious ongoing commitment for adult volunteers, and the impact on a young person in crisis can be life-saving.', array['training provided', 'recurring'], 18, true, true, true, '4 hrs / week', 'https://www.thetrevorproject.org/volunteer/', 'https://www.thetrevorproject.org/volunteer/', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000015', 'e5000000-0000-4000-8000-000000000015', 'Help Families at RMHC', 'medicine', 'When a child is seriously ill, Ronald McDonald House gives their family a warm place to stay just steps from the hospital, and volunteers make that house feel like home. You might cook and serve a family meal, welcome guests at the front desk, organize activities for siblings, or help run fundraising events. Roles and age minimums vary by local chapter, and groups are often welcome.', array['good for crews'], 14, false, false, true, '2-3 hrs / shift', 'https://www.rmhc.org/get-involved', 'https://www.rmhc.org/get-involved', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000016', 'e5000000-0000-4000-8000-000000000016', 'Volunteer at Special Olympics', 'sports', 'Special Olympics puts on training and competitions for athletes with intellectual disabilities, and volunteers make every event possible. You can coach a sport, help run competition day, hand out medals, cheer from the sidelines, or support school-based Unified programs where athletes and partners play together. Roles suit all ages, many are one-day commitments, and the energy at these events is unforgettable.', array['good for crews'], 12, false, false, true, 'Half day', 'https://www.specialolympics.org/ways-to-get-involved/volunteer', 'https://www.specialolympics.org/ways-to-get-involved/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000017', 'e5000000-0000-4000-8000-000000000017', 'Advocate for Animals', 'animals', 'The Humane Society tackles animal welfare on a national scale, from puppy mills and wildlife protection to farm-animal welfare and disaster rescue. Volunteers power that work through advocacy, phone and text banking for animal-protection laws, event support, and helping spread the word online. If you care about animals and want your voice to influence real policy, this is a flexible way to help.', array['recurring'], 16, false, false, true, 'Flexible', 'https://www.humanesociety.org/volunteer', 'https://www.humanesociety.org/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000018', 'e5000000-0000-4000-8000-000000000018', 'Volunteer in a National Park', 'environment', 'The Volunteers-In-Parks program invites you to help protect the places that belong to all of us. Depending on the park you might maintain trails, restore habitat, greet and guide visitors, assist at a visitor center, or support citizen-science and conservation projects. Opportunities range from a single day of trail work to ongoing seasonal roles, and many parks welcome families and groups.', array['outdoors', 'good for crews'], 16, false, false, true, 'Half day', 'https://www.nps.gov/getinvolved/volunteer.htm', 'https://www.nps.gov/getinvolved/volunteer.htm', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000019', 'e5000000-0000-4000-8000-000000000019', 'Write to Troops and Veterans', 'veterans', 'Operation Gratitude lets anyone say thank you to the people who serve, no matter where you are. The simplest way to help is writing heartfelt letters of appreciation to deployed troops, veterans, and first responders, which get included in care packages shipped nationwide. It is an all-ages activity you can do solo, with a club, or as a family, and every letter genuinely brightens someone day.', array['no experience needed', 'one-time'], 0, true, true, true, '1 hr', 'https://www.operationgratitude.com/volunteer/', 'https://www.operationgratitude.com/volunteer/', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000020', 'e5000000-0000-4000-8000-000000000020', 'Join a Youth Campaign', 'community', 'DoSomething runs volunteer campaigns designed by and for young people on issues like the environment, mental health, education, and equality. Most campaigns can be done right from your phone, whether that is collecting supplies, spreading awareness, or taking a concrete action in your community. Many campaigns also enter you into scholarship drawings, making it a smart way to do good and get rewarded.', array['no experience needed', 'counts for school hours'], 13, true, true, true, 'Flexible', 'https://www.dosomething.org', 'https://www.dosomething.org', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000021', 'e5000000-0000-4000-8000-000000000021', 'Coach or Cheer with GOTR', 'sports', 'Girls on the Run combines running with lessons that help girls build confidence, kindness, and decision-making skills. Volunteers can coach a team over a season, run alongside a girl as a race-day buddy, or help organize community 5K events. Coaching is the most rewarding role and no running expertise is required, just enthusiasm and a willingness to be a positive role model.', array['recurring'], 14, false, false, true, '2 hrs / week', 'https://www.girlsontherun.org/volunteer', 'https://www.girlsontherun.org/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000022', 'e5000000-0000-4000-8000-000000000022', 'Map Biodiversity', 'environment', 'Every photo you take of a wild plant, animal, or fungus on iNaturalist becomes a data point that scientists use to track biodiversity and climate change. Snap a picture, and the community and its AI help identify the species, adding your observation to a global research database. It turns a walk outside into real citizen science, and it is completely free and beginner-friendly.', array['no experience needed', 'outdoors'], 13, true, true, true, 'Flexible', 'https://www.inaturalist.org', 'https://www.inaturalist.org', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000023', 'e5000000-0000-4000-8000-000000000023', 'Translate for Refugees', 'community', 'Language barriers can keep refugees and immigrants from getting medical care, legal help, or safety information. Tarjimly matches you in real time with someone who needs translation in a language you speak, right through the app, for a single conversation at a time. Sessions are short and on-demand, and being fluent in a second language suddenly becomes a way to change someone life.', array['recurring'], 16, true, true, true, 'A few min', 'https://www.tarjimly.org/get-involved', 'https://www.tarjimly.org/get-involved', '2026-01-01T00:00:00Z', null, null),
  ('e6000000-0000-4000-8000-000000000024', 'e5000000-0000-4000-8000-000000000024', 'Sort Food in Atlanta', 'food', 'The Atlanta Community Food Bank distributes tens of millions of meals a year, and its Product Rescue Center depends on volunteers to make that happen. Volunteers sort, inspect, and box donated groceries so they can go out to partner pantries across metro Atlanta and north Georgia. Shifts are a couple of hours, welcoming to school and club groups, and a great local option for service hours.', array['good for crews', 'counts for school hours'], 14, false, false, true, '2.5 hrs / shift', 'https://www.acfb.org/volunteer/', 'https://www.acfb.org/volunteer/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('e6000000-0000-4000-8000-000000000025', 'e5000000-0000-4000-8000-000000000025', 'Help Shelter Animals', 'animals', 'LifeLine operates the Fulton and DeKalb County animal shelters and works to keep them no-kill, which takes a lot of caring hands. Volunteers walk and socialize dogs, spend calming time with cats, help at adoption events, and take photos that help pets find homes faster. It is a rewarding recurring role for local animal lovers, with orientation and training provided.', array['recurring'], 13, false, false, true, '2 hrs / shift', 'https://lifelineanimal.org/volunteer/', 'https://lifelineanimal.org/volunteer/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA');
