-- Migration 019: 9 real, local San Francisco Bay Area organizations,
-- researched individually. Pure inserts with fixed ids - safe to re-run.

insert into public.organizations
  (id, owner_id, name, description, website, logo_url, category, tags, remote, international,
   min_age, country, state, city, verified, counts_for_service_hours, commitment_type, featured)
values
  ('b1000000-0000-4000-8000-000000000001', null, 'San Francisco-Marin Food Bank', 'The primary hunger-relief organization for San Francisco and Marin County, running three warehouses that distribute food across the region.', 'https://www.sfmfoodbank.org', 'https://www.google.com/s2/favicons?domain=www.sfmfoodbank.org&sz=128', 'food', array['good for crews'], false, false, 14, 'United States', 'CA', 'San Francisco', true, true, 'both', false),
  ('b1000000-0000-4000-8000-000000000002', null, 'Friends of SFACC', 'The nonprofit support organization for San Francisco Animal Care and Control, the city public animal shelter.', 'https://friendsofsfacc.org', 'https://www.google.com/s2/favicons?domain=friendsofsfacc.org&sz=128', 'animals', array['family friendly', 'recurring'], false, false, 12, 'United States', 'CA', 'San Francisco', true, true, 'ongoing', false),
  ('b1000000-0000-4000-8000-000000000003', null, 'San Francisco Recreation and Parks', 'The city department managing parks across San Francisco, including Golden Gate Park, coordinating volunteer maintenance and restoration projects.', 'https://sfrecpark.org', 'https://www.google.com/s2/favicons?domain=sfrecpark.org&sz=128', 'environment', array['outdoors', 'family friendly'], false, false, 0, 'United States', 'CA', 'San Francisco', true, true, 'both', false),
  ('b1000000-0000-4000-8000-000000000004', null, 'Golden Gate National Parks Conservancy', 'The nonprofit partner of the National Park Service caring for the Golden Gate National Recreation Area, one of the largest urban national parks in the world.', 'https://www.parksconservancy.org', 'https://www.google.com/s2/favicons?domain=www.parksconservancy.org&sz=128', 'environment', array['outdoors', 'family friendly', 'good for crews'], false, false, 0, 'United States', 'CA', 'San Francisco', true, true, 'both', false),
  ('b1000000-0000-4000-8000-000000000005', null, 'San Francisco Environment Department', 'The city department leading San Francisco environmental policy and programs across zero waste, biodiversity, clean energy, and sustainable living.', 'https://www.sfenvironment.org', 'https://www.google.com/s2/favicons?domain=www.sfenvironment.org&sz=128', 'environment', array['leadership role'], false, false, 0, 'United States', 'CA', 'San Francisco', true, true, 'both', false),
  ('b1000000-0000-4000-8000-000000000006', null, 'Saved By Nature', 'A Bay Area nonprofit connecting teens with the outdoors through hike leadership, community outreach, and environmental education roles.', 'https://www.savedbynature.org', 'https://www.google.com/s2/favicons?domain=www.savedbynature.org&sz=128', 'environment', array['leadership role', 'counts for school hours'], false, false, 14, 'United States', 'CA', 'San Francisco', true, true, 'ongoing', false),
  ('b1000000-0000-4000-8000-000000000007', null, 'UCSF Benioff Children''s Hospitals', 'A leading pediatric hospital system with campuses in San Francisco and Oakland, running teen-specific volunteer programs including Junior Ambassadors.', 'https://www.ucsfbenioffchildrens.org', 'https://www.google.com/s2/favicons?domain=www.ucsfbenioffchildrens.org&sz=128', 'medicine', array['counts for school hours'], false, false, 14, 'United States', 'CA', 'San Francisco', true, true, 'both', false),
  ('b1000000-0000-4000-8000-000000000008', null, 'Boys and Girls Clubs of San Francisco', 'A youth development organization running academic support, enrichment, and teen services programs across San Francisco clubhouses.', 'https://www.kidsclub.org', 'https://www.google.com/s2/favicons?domain=www.kidsclub.org&sz=128', 'community', array['recurring', 'leadership role'], false, false, 14, 'United States', 'CA', 'San Francisco', true, true, 'ongoing', false),
  ('b1000000-0000-4000-8000-000000000009', null, 'Mission Graduates', 'A San Francisco nonprofit supporting Mission District youth from early education through college with tutoring, mentorship, and community engagement.', 'https://www.missiongraduates.org', 'https://www.google.com/s2/favicons?domain=www.missiongraduates.org&sz=128', 'education', array['recurring', 'counts for school hours'], false, false, 16, 'United States', 'CA', 'San Francisco', true, true, 'ongoing', false)
on conflict (id) do nothing;

insert into public.opportunities
  (id, org_id, title, category, description, tags, min_age, remote, is_online, is_ongoing,
   hours_estimate, signup_link, external_url, starts_at, city, state)
values
  ('b2000000-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000001', 'Volunteer at the SF-Marin Food Bank', 'food', 'Warehouse volunteers repack dry goods, sort produce, fill food boxes for seniors, and pack bags for home-delivered groceries at any of three Bay Area locations. All three warehouses welcome teenage volunteers, making this one of the most accessible options in the city.', array['good for crews'], 14, false, false, true, '2-3 hrs', 'https://www.sfmfoodbank.org/volunteer/', 'https://www.sfmfoodbank.org/volunteer/', '2026-01-01T00:00:00Z', 'San Francisco', 'CA'),
  ('b2000000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000002', 'Volunteer with San Francisco Animal Care and Control', 'animals', 'Volunteers walk dogs, socialize cats and small animals, help with laundry and toy sorting, and support outreach events. Volunteers under 18 need a parent or guardian to attend orientation with them and commit to at least two hours a week for six months.', array['family friendly', 'recurring'], 12, false, false, true, '2 hrs / week', 'https://friendsofsfacc.org/volunteer/', 'https://friendsofsfacc.org/volunteer/', '2026-01-01T00:00:00Z', 'San Francisco', 'CA'),
  ('b2000000-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000003', 'Volunteer with San Francisco Recreation and Parks', 'environment', 'Volunteers help with weeding, planting, mulching, habitat restoration, trash pickup, painting, and trail work at parks across the city, including Golden Gate Park and Mission Dolores Park. It is one of the easiest ways to find an outdoor project close to home in San Francisco.', array['outdoors', 'family friendly'], 0, false, false, true, '2-3 hrs', 'https://sfrecpark.org/1665/Park-Volunteers', 'https://sfrecpark.org/1665/Park-Volunteers', '2026-01-01T00:00:00Z', 'San Francisco', 'CA'),
  ('b2000000-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000004', 'Volunteer with the Golden Gate National Parks Conservancy', 'environment', 'Volunteers help protect beaches and native habitats by removing litter and debris and minimizing marine debris across the Golden Gate National Recreation Area. It is a strong pick if you want your service tied to a nationally significant park system.', array['outdoors', 'family friendly', 'good for crews'], 0, false, false, true, '2-3 hrs', 'https://www.parksconservancy.org/volunteer/volunteer-projects-and-activities', 'https://www.parksconservancy.org/volunteer/volunteer-projects-and-activities', '2026-01-01T00:00:00Z', 'San Francisco', 'CA'),
  ('b2000000-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000005', 'Volunteer with SF Environment', 'environment', 'Volunteers support city initiatives around zero waste, biodiversity, clean energy, and sustainable living, connecting with others working on the same issues. It is a good option if you are interested in environmental policy and systems, not just hands-on cleanup work.', array['leadership role'], 0, false, false, true, 'Varies', 'https://www.sfenvironment.org/volunteer', 'https://www.sfenvironment.org/volunteer', '2026-01-01T00:00:00Z', 'San Francisco', 'CA'),
  ('b2000000-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000006', 'Volunteer with Saved By Nature', 'environment', 'High schoolers can train to become hike leaders for SF parks, do community outreach connecting with SF neighborhoods, or support administrative work, all with mentorship from experienced outdoor educators. It is a great option if you want structured training and a real leadership role outdoors.', array['leadership role', 'counts for school hours'], 14, false, false, true, 'Flexible', 'https://www.savedbynature.org/get-involved/volunteer-opportunities-bay-area', 'https://www.savedbynature.org/get-involved/volunteer-opportunities-bay-area', '2026-01-01T00:00:00Z', 'San Francisco', 'CA'),
  ('b2000000-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000007', 'Join UCSF Benioff Children''s Hospitals Junior Ambassadors', 'medicine', 'Junior Ambassadors ages 14-18 support patients and families by making bedside activity kits, crafting holiday cards, and collecting essential items for families in care, while the Summer Student Program (ages 16-18) offers a structured weekly hospital shift. It is a strong option no matter which age bracket you are in.', array['counts for school hours'], 14, false, false, true, 'Varies', 'https://www.ucsfbenioffchildrens.org/about/become-a-volunteer', 'https://www.ucsfbenioffchildrens.org/about/become-a-volunteer', '2026-01-01T00:00:00Z', 'San Francisco', 'CA'),
  ('b2000000-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000008', 'Volunteer with Boys and Girls Clubs of San Francisco', 'community', 'Volunteers support Power Hour homework help, tutoring, STEM enrichment, and teen services like college prep and career readiness, as well as sports, fitness, and art programs. It is a great option if you want variety across academics, wellness, and creative activities.', array['recurring', 'leadership role'], 14, false, false, true, '1-2 hrs / week', 'https://www.kidsclub.org/get-involved/volunteer', 'https://www.kidsclub.org/get-involved/volunteer', '2026-01-01T00:00:00Z', 'San Francisco', 'CA'),
  ('b2000000-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000009', 'Tutor or Mentor with Mission Graduates', 'education', 'Volunteers provide tutoring and mentorship support to Mission District students working toward college and career goals. It is a meaningful option if you want your tutoring tied to a specific, long-term community pipeline from school through college.', array['recurring', 'counts for school hours'], 16, false, false, true, 'Varies', 'https://www.missiongraduates.org/volunteer/', 'https://www.missiongraduates.org/volunteer/', '2026-01-01T00:00:00Z', 'San Francisco', 'CA')
on conflict (id) do nothing;
