-- Migration 032: real, individually researched orgs for Portland, OR
-- (15 orgs) -- third batch, smaller size per founder's request.

insert into public.organizations
  (id, owner_id, name, description, website, logo_url, category, tags, remote, international,
   min_age, country, state, city, verified, counts_for_service_hours, commitment_type, featured)
values
  ('f5000000-0000-4000-8000-000000000001', null, 'BRAVO Youth Orchestras', 'BRAVO Youth Orchestras runs a tuition-free music program across seven North Portland schools, giving students who might never afford lessons a real orchestra experience and mentorship. Volunteers help at rehearsals, concerts, and instrument care for a program built around access, not ability to pay.', 'https://oregonbravo.org/', 'https://www.google.com/s2/favicons?domain=oregonbravo.org&sz=128', 'music', array['music or performance','training provided','family friendly','recurring'], false, false, 15, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000002', null, 'Metropolitan Youth Symphony', 'Metropolitan Youth Symphony believes every student deserves access to music education regardless of ability to pay, and no student is ever turned away for lack of funds. Volunteers support rehearsals, concerts, and the community of students, families, and coaches that keeps the program running.', 'https://playmys.org/', 'https://www.google.com/s2/favicons?domain=playmys.org&sz=128', 'music', array['music or performance','family friendly','recurring','one-time'], false, false, 15, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000003', null, 'Catholic Charities of Oregon', 'Catholic Charities of Oregon partners with the most vulnerable across the state to fight poverty and injustice, regardless of faith. Their volunteer console lists shifts across dozens of programs -- you don''t need to be Catholic to sign up and help.', 'https://www.catholiccharitiesoregon.org/', 'https://www.google.com/s2/favicons?domain=www.catholiccharitiesoregon.org&sz=128', 'faith', array['faith-based','no experience needed','recurring','one-time'], false, false, 14, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000004', null, 'Jewish Federation of Greater Portland', 'The Jewish Federation of Greater Portland runs the Jewish Volunteer Corps, a one-stop hub for doing good alongside the local Jewish community. Opportunities span food security, social advocacy, and interfaith projects open to volunteers of any background.', 'https://jewishportland.org/', 'https://www.google.com/s2/favicons?domain=jewishportland.org&sz=128', 'faith', array['faith-based','no experience needed','family friendly','recurring'], false, false, 14, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000005', null, 'Oregon Humane Society', 'Oregon Humane Society runs a dedicated Youth Volunteer Program for ages 12-17, with older teens volunteering solo and younger ones alongside a parent. Shifts include walking dogs, socializing cats and small animals, and keeping shelter spaces clean and welcoming.', 'https://www.oregonhumane.org/', 'https://www.google.com/s2/favicons?domain=www.oregonhumane.org&sz=128', 'animals', array['animal handling','training provided','recurring','family friendly'], false, false, 12, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000006', null, 'SOLVE', 'SOLVE organizes litter cleanups and habitat restoration across Oregon and SW Washington, with youth-friendly registration for ages 13-17 (with an adult''s sign-off) and even teen-led cleanup opportunities that build real leadership experience. A go-to pick for a crew that wants an easy, high-impact outdoor shift.', 'https://www.solve.org/', 'https://www.google.com/s2/favicons?domain=www.solve.org&sz=128', 'environment', array['outdoors','good for crews','no experience needed','leadership role'], false, false, 13, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000007', null, 'Oregon Food Bank', 'Oregon Food Bank fights hunger statewide, and volunteers are the backbone of its work -- sorting and repacking donated food, helping with seasonal garden projects, or distributing meals directly in the community. Shifts run at both the Portland and Beaverton locations.', 'https://www.oregonfoodbank.org/', 'https://www.google.com/s2/favicons?domain=www.oregonfoodbank.org&sz=128', 'food', array['good for crews','no experience needed','physical work','recurring'], false, false, 14, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000008', null, 'OHSU Doernbecher Children''s Hospital', 'Doernbecher Children''s Hospital''s Healing Through Music program lets teen volunteers play for patients during two-hour shifts, bringing comfort to kids stuck waiting for appointments. It''s a standout pick for musicians who want to see the real impact of their skills in a hospital setting.', 'https://www.ohsu.edu/doernbecher', 'https://www.google.com/s2/favicons?domain=www.ohsu.edu&sz=128', 'medicine', array['music or performance','training provided','skilled volunteers wanted','indoors'], false, false, 14, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000009', null, 'The Mission Continues -- Portland Service Platoon', 'The Mission Continues'' Portland Service Platoon partners with local organizations to tackle veteran homelessness and support transitional housing across the metro area. Volunteers join veterans on hands-on service projects that build community while making a real difference.', 'https://www.missioncontinues.org/service-platoon/Portland/', 'https://www.google.com/s2/favicons?domain=www.missioncontinues.org&sz=128', 'veterans', array['good for crews','physical work','one-time','leadership role'], false, false, 16, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000010', null, 'Free Geek', 'Free Geek refurbishes donated technology and gives it back to the community at low or no cost, running a "Plug into Portland" program where K-12 students earn a free computer after 24 hours of volunteer service. A solid pick for anyone who likes taking things apart and putting them back together.', 'https://www.freegeek.org/', 'https://www.google.com/s2/favicons?domain=www.freegeek.org&sz=128', 'tech', array['tech skills useful','training provided','skilled volunteers wanted','recurring'], false, false, 14, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000011', null, 'Special Olympics Oregon', 'Special Olympics Oregon runs year-round sports training and competition for athletes with intellectual disabilities, and teen volunteering has grown fast through school-based Unified Champion Schools programs. Coaching commitments run just 1-2 hours a week, or jump in as a day-of-event volunteer.', 'https://soor.org/', 'https://www.google.com/s2/favicons?domain=soor.org&sz=128', 'sports', array['sports or coaching','no experience needed','family friendly','weekly'], false, false, 14, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000012', null, 'Meals on Wheels People', 'Meals on Wheels People delivers meals and friendly check-ins to homebound older adults across the Portland-Vancouver metro. Teens 14+ can deliver routes alongside a chaperone, and 18+ volunteers can go solo -- flexible two-to-four-hour shifts that fit around school.', 'https://www.mowp.org/', 'https://www.google.com/s2/favicons?domain=www.mowp.org&sz=128', 'seniors', array['chill first-timer pick','family friendly','recurring','weekly'], false, false, 14, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000013', null, 'Our Village Gardens', 'Our Village Gardens grows fresh produce in Portland''s New Columbia neighborhood, selling it right back to the community that grows it. Volunteer groups of any size can join youth and adult garden leaders for seeding, planting, and weeding during the growing season.', 'https://www.villagegardens.org/', 'https://www.google.com/s2/favicons?domain=www.villagegardens.org&sz=128', 'gardening', array['gardening skills','outdoors','good for crews','seasonal'], false, false, 12, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000014', null, 'SMART Reading', 'SMART Reading pairs volunteers with K-3 students at Portland-area schools for a weekly hour of reading practice, and every student gets to pick free books to take home. It''s a low-key, high-impact way to help a younger kid fall in love with reading.', 'https://smartreading.org/', 'https://www.google.com/s2/favicons?domain=smartreading.org&sz=128', 'education', array['teaching or tutoring','chill first-timer pick','weekly','no experience needed'], false, false, 15, 'United States', 'OR', 'Portland', true, true, 'ongoing', false),
  ('f5000000-0000-4000-8000-000000000015', null, 'Hands On Greater Portland', 'Hands On Greater Portland connects volunteers with hundreds of local nonprofits across the metro, from food banks to environmental cleanups to interfaith service projects. It''s a great first stop if you want to try a few different causes before picking a favorite.', 'https://www.handsonportland.org/', 'https://www.google.com/s2/favicons?domain=www.handsonportland.org&sz=128', 'community', array['good for crews','no experience needed','chill first-timer pick','one-time'], false, false, 14, 'United States', 'OR', 'Portland', true, true, 'ongoing', false)
on conflict (id) do nothing;

insert into public.opportunities
  (id, org_id, title, category, description, tags, min_age, remote, is_online, is_ongoing,
   hours_estimate, signup_link, external_url, starts_at, city, state)
values
  ('f6000000-0000-4000-8000-000000000001', 'f5000000-0000-4000-8000-000000000001', 'Volunteer with BRAVO Youth Orchestras', 'music', 'BRAVO Youth Orchestras runs a tuition-free music program across seven North Portland schools, giving students who might never afford lessons a real orchestra experience and mentorship. Volunteers help at rehearsals, concerts, and instrument care for a program built around access, not ability to pay.', array['music or performance','training provided','family friendly','recurring'], 15, false, false, true, '2-3 hrs', 'https://oregonbravo.org/', 'https://oregonbravo.org/', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000002', 'f5000000-0000-4000-8000-000000000002', 'Volunteer with Metropolitan Youth Symphony', 'music', 'Metropolitan Youth Symphony believes every student deserves access to music education regardless of ability to pay, and no student is ever turned away for lack of funds. Volunteers support rehearsals, concerts, and the community of students, families, and coaches that keeps the program running.', array['music or performance','family friendly','recurring','one-time'], 15, false, false, true, '2-3 hrs', 'https://playmys.org/', 'https://playmys.org/', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000003', 'f5000000-0000-4000-8000-000000000003', 'Volunteer with Catholic Charities of Oregon', 'faith', 'Catholic Charities of Oregon partners with the most vulnerable across the state to fight poverty and injustice, regardless of faith. Their volunteer console lists shifts across dozens of programs -- you don''t need to be Catholic to sign up and help.', array['faith-based','no experience needed','recurring','one-time'], 14, false, false, true, '2-3 hrs', 'https://www.catholiccharitiesoregon.org/services/volunteer/', 'https://www.catholiccharitiesoregon.org/services/volunteer/', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000004', 'f5000000-0000-4000-8000-000000000004', 'Join the Jewish Volunteer Corps', 'faith', 'The Jewish Federation of Greater Portland runs the Jewish Volunteer Corps, a one-stop hub for doing good alongside the local Jewish community. Opportunities span food security, social advocacy, and interfaith projects open to volunteers of any background.', array['faith-based','no experience needed','family friendly','recurring'], 14, false, false, true, '2-3 hrs', 'https://jewishportland.org/ourcommunity/volunteering', 'https://jewishportland.org/ourcommunity/volunteering', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000005', 'f5000000-0000-4000-8000-000000000005', 'Youth Volunteer at Oregon Humane Society', 'animals', 'Oregon Humane Society runs a dedicated Youth Volunteer Program for ages 12-17, with older teens volunteering solo and younger ones alongside a parent. Shifts include walking dogs, socializing cats and small animals, and keeping shelter spaces clean and welcoming.', array['animal handling','training provided','recurring','family friendly'], 12, false, false, true, '2 hrs', 'https://www.oregonhumane.org/get-involved/volunteer/youths-12-17/', 'https://www.oregonhumane.org/get-involved/volunteer/youths-12-17/', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000006', 'f5000000-0000-4000-8000-000000000006', 'Clean Up with SOLVE', 'environment', 'SOLVE organizes litter cleanups and habitat restoration across Oregon and SW Washington, with youth-friendly registration for ages 13-17 (with an adult''s sign-off) and even teen-led cleanup opportunities that build real leadership experience. A go-to pick for a crew that wants an easy, high-impact outdoor shift.', array['outdoors','good for crews','no experience needed','leadership role'], 13, false, false, true, '2-3 hrs', 'https://www.solve.org/volunteer', 'https://www.solve.org/volunteer', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000007', 'f5000000-0000-4000-8000-000000000007', 'Volunteer with Oregon Food Bank', 'food', 'Oregon Food Bank fights hunger statewide, and volunteers are the backbone of its work -- sorting and repacking donated food, helping with seasonal garden projects, or distributing meals directly in the community. Shifts run at both the Portland and Beaverton locations.', array['good for crews','no experience needed','physical work','recurring'], 14, false, false, true, '2-3 hrs', 'https://www.oregonfoodbank.org/get-involved/volunteer', 'https://www.oregonfoodbank.org/get-involved/volunteer', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000008', 'f5000000-0000-4000-8000-000000000008', 'Healing Through Music at Doernbecher', 'medicine', 'Doernbecher Children''s Hospital''s Healing Through Music program lets teen volunteers play for patients during two-hour shifts, bringing comfort to kids stuck waiting for appointments. It''s a standout pick for musicians who want to see the real impact of their skills in a hospital setting.', array['music or performance','training provided','skilled volunteers wanted','indoors'], 14, false, false, true, '2 hrs', 'https://www.ohsu.edu/doernbecher/volunteering-safety-center', 'https://www.ohsu.edu/doernbecher/volunteering-safety-center', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000009', 'f5000000-0000-4000-8000-000000000009', 'Volunteer with The Mission Continues Portland', 'veterans', 'The Mission Continues'' Portland Service Platoon partners with local organizations to tackle veteran homelessness and support transitional housing across the metro area. Volunteers join veterans on hands-on service projects that build community while making a real difference.', array['good for crews','physical work','one-time','leadership role'], 16, false, false, true, 'Full day', 'https://www.missioncontinues.org/service-platoon/Portland/', 'https://www.missioncontinues.org/service-platoon/Portland/', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000010', 'f5000000-0000-4000-8000-000000000010', 'Volunteer with Free Geek', 'tech', 'Free Geek refurbishes donated technology and gives it back to the community at low or no cost, running a "Plug into Portland" program where K-12 students earn a free computer after 24 hours of volunteer service. A solid pick for anyone who likes taking things apart and putting them back together.', array['tech skills useful','training provided','skilled volunteers wanted','recurring'], 14, false, false, true, '2-3 hrs', 'https://www.freegeek.org/internships-volunteering', 'https://www.freegeek.org/internships-volunteering', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000011', 'f5000000-0000-4000-8000-000000000011', 'Coach with Special Olympics Oregon', 'sports', 'Special Olympics Oregon runs year-round sports training and competition for athletes with intellectual disabilities, and teen volunteering has grown fast through school-based Unified Champion Schools programs. Coaching commitments run just 1-2 hours a week, or jump in as a day-of-event volunteer.', array['sports or coaching','no experience needed','family friendly','weekly'], 14, false, false, true, '1-2 hrs', 'https://soor.org/volunteer/', 'https://soor.org/volunteer/', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000012', 'f5000000-0000-4000-8000-000000000012', 'Deliver with Meals on Wheels People', 'seniors', 'Meals on Wheels People delivers meals and friendly check-ins to homebound older adults across the Portland-Vancouver metro. Teens 14+ can deliver routes alongside a chaperone, and 18+ volunteers can go solo -- flexible two-to-four-hour shifts that fit around school.', array['chill first-timer pick','family friendly','recurring','weekly'], 14, false, false, true, '2-4 hrs', 'https://www.mowp.org/volunteer/volunteer-opportunities/', 'https://www.mowp.org/volunteer/volunteer-opportunities/', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000013', 'f5000000-0000-4000-8000-000000000013', 'Garden with Our Village Gardens', 'gardening', 'Our Village Gardens grows fresh produce in Portland''s New Columbia neighborhood, selling it right back to the community that grows it. Volunteer groups of any size can join youth and adult garden leaders for seeding, planting, and weeding during the growing season.', array['gardening skills','outdoors','good for crews','seasonal'], 12, false, false, true, '2-3 hrs', 'https://www.villagegardens.org/volunteer', 'https://www.villagegardens.org/volunteer', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000014', 'f5000000-0000-4000-8000-000000000014', 'Read with SMART Reading', 'education', 'SMART Reading pairs volunteers with K-3 students at Portland-area schools for a weekly hour of reading practice, and every student gets to pick free books to take home. It''s a low-key, high-impact way to help a younger kid fall in love with reading.', array['teaching or tutoring','chill first-timer pick','weekly','no experience needed'], 15, false, false, true, '1 hr/week', 'https://smartreading.org/volunteer/', 'https://smartreading.org/volunteer/', '2026-01-01T00:00:00Z', 'Portland', 'OR'),
  ('f6000000-0000-4000-8000-000000000015', 'f5000000-0000-4000-8000-000000000015', 'Explore Causes with Hands On Greater Portland', 'community', 'Hands On Greater Portland connects volunteers with hundreds of local nonprofits across the metro, from food banks to environmental cleanups to interfaith service projects. It''s a great first stop if you want to try a few different causes before picking a favorite.', array['good for crews','no experience needed','chill first-timer pick','one-time'], 14, false, false, true, '2-3 hrs', 'https://www.handsonportland.org/', 'https://www.handsonportland.org/', '2026-01-01T00:00:00Z', 'Portland', 'OR')
on conflict (id) do nothing;
