-- Migration 033: real, individually researched orgs for the Northern
-- Plains -- Billings & Bozeman, MT; Fargo, ND; Sioux Falls, SD (15 orgs).
-- Fourth batch, filling a genuinely empty stretch of the coverage map.

insert into public.organizations
  (id, owner_id, name, description, website, logo_url, category, tags, remote, international,
   min_age, country, state, city, verified, counts_for_service_hours, commitment_type, featured)
values
  ('f7000000-0000-4000-8000-000000000001', null, 'Yellowstone Valley Animal Shelter', 'Yellowstone Valley Animal Shelter cares for Billings-area dogs and cats, and welcomes group volunteer days of four or more for daily shelter operations and hands-on animal time. A quick orientation gets you started, and younger kids can join the monthly Feline Fan Club to read to shelter cats.', 'https://yvas.org/', 'https://www.google.com/s2/favicons?domain=yvas.org&sz=128', 'animals', array['animal handling','family friendly','good for crews','recurring'], false, false, 10, 'United States', 'MT', 'Billings', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000002', null, 'Billings Food Bank', 'Billings Food Bank sorts and distributes food to families across the region, and welcomes volunteers to bring whatever talents they have to the warehouse floor. It''s a flexible, no-experience-needed pick for a crew that wants to spend a few hours making a visible difference.', 'https://billingsfoodbank.com/', 'https://www.google.com/s2/favicons?domain=billingsfoodbank.com&sz=128', 'food', array['good for crews','no experience needed','physical work','recurring'], false, false, 13, 'United States', 'MT', 'Billings', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000003', null, 'Montana Rescue Mission', 'Montana Rescue Mission provides shelter, meals, and recovery programs for people experiencing homelessness in Billings, rooted in faith but open to volunteers of any background. Volunteers help serve meals, sort donations, and support daily shelter operations.', 'https://montanarescuemission.org/', 'https://www.google.com/s2/favicons?domain=montanarescuemission.org&sz=128', 'faith', array['faith-based','no experience needed','recurring','physical work'], false, false, 14, 'United States', 'MT', 'Billings', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000004', null, 'Gallatin Valley Land Trust', 'Gallatin Valley Land Trust protects open space and trails across the Bozeman area, and volunteers pitch in pulling weeds, building fences, and restoring wildlife habitat. A solid pick for anyone who loves being outdoors and wants to see real conservation work up close.', 'https://www.gvlt.org/', 'https://www.google.com/s2/favicons?domain=www.gvlt.org&sz=128', 'environment', array['outdoors','no experience needed','physical work','one-time'], false, false, 14, 'United States', 'MT', 'Bozeman', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000005', null, 'Heart of the Valley Animal Shelter', 'Heart of the Valley Animal Shelter serves the Gallatin and Madison Valleys, running a Junior Volunteer Program for younger kids with a parent and a full PAW Program for volunteers 16 and up working directly with shelter dogs and cats. Group projects and service-learning shifts are also available.', 'https://www.heartofthevalleyshelter.org/', 'https://www.google.com/s2/favicons?domain=www.heartofthevalleyshelter.org&sz=128', 'animals', array['animal handling','training provided','family friendly','recurring'], false, false, 6, 'United States', 'MT', 'Bozeman', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000006', null, 'Sweet Pea Festival of the Arts', 'Sweet Pea Festival has filled Bozeman''s Lindley Park with live music, theatre, dance, and visual arts every August since 1978, and needs over 2,000 volunteers to pull it off. Shifts range from info booth duty to stage crew -- a fun, high-energy one-time commitment.', 'https://www.sweetpeafestival.org/', 'https://www.google.com/s2/favicons?domain=www.sweetpeafestival.org&sz=128', 'art', array['arts and crafts','good for crews','one-time','seasonal'], false, false, 14, 'United States', 'MT', 'Bozeman', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000007', null, 'Montana Conservation Corps -- Greater Yellowstone', 'Montana Conservation Corps runs hands-on conservation projects across the Greater Yellowstone region near Bozeman, from trail work to habitat restoration. Volunteer days are a great way to build real outdoor skills alongside a crew.', 'https://www.mtcorps.org/', 'https://www.google.com/s2/favicons?domain=www.mtcorps.org&sz=128', 'environment', array['outdoors','good for crews','physical work','training provided'], false, false, 14, 'United States', 'MT', 'Bozeman', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000008', null, 'Great Plains Food Bank', 'Great Plains Food Bank is North Dakota''s only food bank, running warehouse shifts in Fargo Monday through Friday for volunteers of all ages. Tasks include sorting and repacking donated food for distribution across the region.', 'https://greatplainsfoodbank.org/', 'https://www.google.com/s2/favicons?domain=greatplainsfoodbank.org&sz=128', 'food', array['good for crews','no experience needed','physical work','recurring'], false, false, 13, 'United States', 'ND', 'Fargo', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000009', null, 'YWCA Cass Clay', 'YWCA Cass Clay supports women and families in the Fargo-Moorhead area, and volunteers help sort donations, cook in the kitchen, teach life skills classes, or set up for events. There are even virtual volunteer options for anyone who can''t make it in person.', 'https://www.ywcacassclay.org/', 'https://www.google.com/s2/favicons?domain=www.ywcacassclay.org&sz=128', 'community', array['no experience needed','family friendly','recurring','one-time'], true, false, 14, 'United States', 'ND', 'Fargo', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000010', null, 'Sanford Health -- Fargo', 'Sanford Health welcomes over 400 volunteers ages 14 and up across its Fargo campus, offering roles that range from greeting patients to supporting hospital staff. A strong pick for anyone considering a future in healthcare who wants real hospital exposure.', 'https://www.sanfordhealth.org/volunteer-opportunities/fargo', 'https://www.google.com/s2/favicons?domain=www.sanfordhealth.org&sz=128', 'medicine', array['training provided','skilled volunteers wanted','indoors','recurring'], false, false, 14, 'United States', 'ND', 'Fargo', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000011', null, 'Fargo Park District', 'Fargo Park District runs ongoing and seasonal volunteer openings across the city''s parks and recreation programs, welcoming a wide range of ages and interests. A flexible, low-pressure way to rack up hours while staying active outdoors.', 'https://www.fargoparks.com/volunteer', 'https://www.google.com/s2/favicons?domain=www.fargoparks.com&sz=128', 'sports', array['outdoors','family friendly','recurring','chill first-timer pick'], false, false, 13, 'United States', 'ND', 'Fargo', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000012', null, 'Helpline Center', 'Helpline Center connects Sioux Falls volunteers with dozens of local nonprofits offering nearly 80 different volunteer roles. It runs SALSA, a program linking over 500 area high schoolers with nonprofit partners for monthly service projects and group outings.', 'https://www.helplinecenter.org/', 'https://www.google.com/s2/favicons?domain=www.helplinecenter.org&sz=128', 'community', array['good for crews','leadership role','no experience needed','recurring'], false, false, 14, 'United States', 'SD', 'Sioux Falls', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000013', null, 'DakotAbilities', 'DakotAbilities supports adults with disabilities across South Dakota through housing, employment, and day services. Volunteers spend time directly with the people DakotAbilities serves, helping create meaningful, everyday moments.', 'https://www.dakotabilities.org/', 'https://www.google.com/s2/favicons?domain=www.dakotabilities.org&sz=128', 'medicine', array['no experience needed','training provided','family friendly','recurring'], false, false, 15, 'United States', 'SD', 'Sioux Falls', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000014', null, 'Children''s Home Society of South Dakota', 'Children''s Home Society of South Dakota works to prevent and heal trauma for kids and families statewide. Volunteers can work directly with families, support programs behind the scenes, or help out at fundraising events -- CHS often customizes a role around your specific skills.', 'https://chssd.org/', 'https://www.google.com/s2/favicons?domain=chssd.org&sz=128', 'education', array['no experience needed','skilled volunteers wanted','one-time','recurring'], false, false, 15, 'United States', 'SD', 'Sioux Falls', true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000015', null, 'Sioux Empire United Way', 'Sioux Empire United Way connects Sioux Falls volunteers with local nonprofits tackling education, health, and financial stability citywide. A solid first stop if you want to explore a few different causes before settling on a favorite.', 'https://www.seuw.org/', 'https://www.google.com/s2/favicons?domain=www.seuw.org&sz=128', 'community', array['good for crews','no experience needed','chill first-timer pick','one-time'], false, false, 14, 'United States', 'SD', 'Sioux Falls', true, true, 'ongoing', false)
on conflict (id) do nothing;

insert into public.opportunities
  (id, org_id, title, category, description, tags, min_age, remote, is_online, is_ongoing,
   hours_estimate, signup_link, external_url, starts_at, city, state)
values
  ('f8000000-0000-4000-8000-000000000001', 'f7000000-0000-4000-8000-000000000001', 'Volunteer with Yellowstone Valley Animal Shelter', 'animals', 'Yellowstone Valley Animal Shelter cares for Billings-area dogs and cats, and welcomes group volunteer days of four or more for daily shelter operations and hands-on animal time. A quick orientation gets you started, and younger kids can join the monthly Feline Fan Club to read to shelter cats.', array['animal handling','family friendly','good for crews','recurring'], 10, false, false, true, '2 hrs', 'https://yvas.org/get-involved/volunteer/', 'https://yvas.org/get-involved/volunteer/', '2026-01-01T00:00:00Z', 'Billings', 'MT'),
  ('f8000000-0000-4000-8000-000000000002', 'f7000000-0000-4000-8000-000000000002', 'Volunteer with Billings Food Bank', 'food', 'Billings Food Bank sorts and distributes food to families across the region, and welcomes volunteers to bring whatever talents they have to the warehouse floor. It''s a flexible, no-experience-needed pick for a crew that wants to spend a few hours making a visible difference.', array['good for crews','no experience needed','physical work','recurring'], 13, false, false, true, '2-3 hrs', 'https://billingsfoodbank.com/volunteer/', 'https://billingsfoodbank.com/volunteer/', '2026-01-01T00:00:00Z', 'Billings', 'MT'),
  ('f8000000-0000-4000-8000-000000000003', 'f7000000-0000-4000-8000-000000000003', 'Volunteer with Montana Rescue Mission', 'faith', 'Montana Rescue Mission provides shelter, meals, and recovery programs for people experiencing homelessness in Billings, rooted in faith but open to volunteers of any background. Volunteers help serve meals, sort donations, and support daily shelter operations.', array['faith-based','no experience needed','recurring','physical work'], 14, false, false, true, '2-3 hrs', 'https://montanarescuemission.org/volunteer/', 'https://montanarescuemission.org/volunteer/', '2026-01-01T00:00:00Z', 'Billings', 'MT'),
  ('f8000000-0000-4000-8000-000000000004', 'f7000000-0000-4000-8000-000000000004', 'Volunteer with Gallatin Valley Land Trust', 'environment', 'Gallatin Valley Land Trust protects open space and trails across the Bozeman area, and volunteers pitch in pulling weeds, building fences, and restoring wildlife habitat. A solid pick for anyone who loves being outdoors and wants to see real conservation work up close.', array['outdoors','no experience needed','physical work','one-time'], 14, false, false, true, '2-3 hrs', 'https://www.gvlt.org/', 'https://www.gvlt.org/', '2026-01-01T00:00:00Z', 'Bozeman', 'MT'),
  ('f8000000-0000-4000-8000-000000000005', 'f7000000-0000-4000-8000-000000000005', 'Junior Volunteer at Heart of the Valley', 'animals', 'Heart of the Valley Animal Shelter serves the Gallatin and Madison Valleys, running a Junior Volunteer Program for younger kids with a parent and a full PAW Program for volunteers 16 and up working directly with shelter dogs and cats. Group projects and service-learning shifts are also available.', array['animal handling','training provided','family friendly','recurring'], 6, false, false, true, '2 hrs', 'https://www.heartofthevalleyshelter.org/volunteer/', 'https://www.heartofthevalleyshelter.org/volunteer/', '2026-01-01T00:00:00Z', 'Bozeman', 'MT'),
  ('f8000000-0000-4000-8000-000000000006', 'f7000000-0000-4000-8000-000000000006', 'Volunteer at Sweet Pea Festival', 'art', 'Sweet Pea Festival has filled Bozeman''s Lindley Park with live music, theatre, dance, and visual arts every August since 1978, and needs over 2,000 volunteers to pull it off. Shifts range from info booth duty to stage crew -- a fun, high-energy one-time commitment.', array['arts and crafts','good for crews','one-time','seasonal'], 14, false, false, true, 'Full day', 'https://www.sweetpeafestival.org/', 'https://www.sweetpeafestival.org/', '2026-01-01T00:00:00Z', 'Bozeman', 'MT'),
  ('f8000000-0000-4000-8000-000000000007', 'f7000000-0000-4000-8000-000000000007', 'Volunteer with Montana Conservation Corps', 'environment', 'Montana Conservation Corps runs hands-on conservation projects across the Greater Yellowstone region near Bozeman, from trail work to habitat restoration. Volunteer days are a great way to build real outdoor skills alongside a crew.', array['outdoors','good for crews','physical work','training provided'], 14, false, false, true, 'Full day', 'https://www.mtcorps.org/about-us/regions/greater-yellowstone.html', 'https://www.mtcorps.org/about-us/regions/greater-yellowstone.html', '2026-01-01T00:00:00Z', 'Bozeman', 'MT'),
  ('f8000000-0000-4000-8000-000000000008', 'f7000000-0000-4000-8000-000000000008', 'Volunteer with Great Plains Food Bank', 'food', 'Great Plains Food Bank is North Dakota''s only food bank, running warehouse shifts in Fargo Monday through Friday for volunteers of all ages. Tasks include sorting and repacking donated food for distribution across the region.', array['good for crews','no experience needed','physical work','recurring'], 13, false, false, true, '2-3 hrs', 'https://greatplainsfoodbank.org/take-action/volunteer/', 'https://greatplainsfoodbank.org/take-action/volunteer/', '2026-01-01T00:00:00Z', 'Fargo', 'ND'),
  ('f8000000-0000-4000-8000-000000000009', 'f7000000-0000-4000-8000-000000000009', 'Volunteer with YWCA Cass Clay', 'community', 'YWCA Cass Clay supports women and families in the Fargo-Moorhead area, and volunteers help sort donations, cook in the kitchen, teach life skills classes, or set up for events. There are even virtual volunteer options for anyone who can''t make it in person.', array['no experience needed','family friendly','recurring','one-time'], 14, true, false, true, '2-3 hrs', 'https://www.ywcacassclay.org/volunteer', 'https://www.ywcacassclay.org/volunteer', '2026-01-01T00:00:00Z', 'Fargo', 'ND'),
  ('f8000000-0000-4000-8000-000000000010', 'f7000000-0000-4000-8000-000000000010', 'Volunteer with Sanford Health Fargo', 'medicine', 'Sanford Health welcomes over 400 volunteers ages 14 and up across its Fargo campus, offering roles that range from greeting patients to supporting hospital staff. A strong pick for anyone considering a future in healthcare who wants real hospital exposure.', array['training provided','skilled volunteers wanted','indoors','recurring'], 14, false, false, true, '2-3 hrs', 'https://www.sanfordhealth.org/volunteer-opportunities/fargo', 'https://www.sanfordhealth.org/volunteer-opportunities/fargo', '2026-01-01T00:00:00Z', 'Fargo', 'ND'),
  ('f8000000-0000-4000-8000-000000000011', 'f7000000-0000-4000-8000-000000000011', 'Volunteer with Fargo Park District', 'sports', 'Fargo Park District runs ongoing and seasonal volunteer openings across the city''s parks and recreation programs, welcoming a wide range of ages and interests. A flexible, low-pressure way to rack up hours while staying active outdoors.', array['outdoors','family friendly','recurring','chill first-timer pick'], 13, false, false, true, '2 hrs', 'https://www.fargoparks.com/volunteer', 'https://www.fargoparks.com/volunteer', '2026-01-01T00:00:00Z', 'Fargo', 'ND'),
  ('f8000000-0000-4000-8000-000000000012', 'f7000000-0000-4000-8000-000000000012', 'Join SALSA via the Helpline Center', 'community', 'Helpline Center connects Sioux Falls volunteers with dozens of local nonprofits offering nearly 80 different volunteer roles. It runs SALSA, a program linking over 500 area high schoolers with nonprofit partners for monthly service projects and group outings.', array['good for crews','leadership role','no experience needed','recurring'], 14, false, false, true, '2-3 hrs', 'https://www.helplinecenter.org/volunteer-connections/youth-volunteer-opportunities/', 'https://www.helplinecenter.org/volunteer-connections/youth-volunteer-opportunities/', '2026-01-01T00:00:00Z', 'Sioux Falls', 'SD'),
  ('f8000000-0000-4000-8000-000000000013', 'f7000000-0000-4000-8000-000000000013', 'Volunteer with DakotAbilities', 'medicine', 'DakotAbilities supports adults with disabilities across South Dakota through housing, employment, and day services. Volunteers spend time directly with the people DakotAbilities serves, helping create meaningful, everyday moments.', array['no experience needed','training provided','family friendly','recurring'], 15, false, false, true, '2-3 hrs', 'https://www.dakotabilities.org/get-involved/volunteer', 'https://www.dakotabilities.org/get-involved/volunteer', '2026-01-01T00:00:00Z', 'Sioux Falls', 'SD'),
  ('f8000000-0000-4000-8000-000000000014', 'f7000000-0000-4000-8000-000000000014', 'Volunteer with Children''s Home Society of SD', 'education', 'Children''s Home Society of South Dakota works to prevent and heal trauma for kids and families statewide. Volunteers can work directly with families, support programs behind the scenes, or help out at fundraising events -- CHS often customizes a role around your specific skills.', array['no experience needed','skilled volunteers wanted','one-time','recurring'], 15, false, false, true, '2-3 hrs', 'https://chssd.org/support/volunteer', 'https://chssd.org/support/volunteer', '2026-01-01T00:00:00Z', 'Sioux Falls', 'SD'),
  ('f8000000-0000-4000-8000-000000000015', 'f7000000-0000-4000-8000-000000000015', 'Explore Causes with Sioux Empire United Way', 'community', 'Sioux Empire United Way connects Sioux Falls volunteers with local nonprofits tackling education, health, and financial stability citywide. A solid first stop if you want to explore a few different causes before settling on a favorite.', array['good for crews','no experience needed','chill first-timer pick','one-time'], 14, false, false, true, '2-3 hrs', 'https://www.seuw.org/volunteer', 'https://www.seuw.org/volunteer', '2026-01-01T00:00:00Z', 'Sioux Falls', 'SD')
on conflict (id) do nothing;
