-- Migration 018: 8 real, local Boston organizations,
-- researched individually. Pure inserts with fixed ids - safe to re-run.

insert into public.organizations
  (id, owner_id, name, description, website, logo_url, category, tags, remote, international,
   min_age, country, state, city, verified, counts_for_service_hours, commitment_type, featured)
values
  ('af000000-0000-4000-8000-000000000001', null, 'The Greater Boston Food Bank', 'The largest hunger-relief organization in New England, distributing food to hundreds of partner agencies across Eastern Massachusetts.', 'https://www.gbfb.org', 'https://www.google.com/s2/favicons?domain=www.gbfb.org&sz=128', 'food', array['good for crews'], false, false, 12, 'United States', 'MA', 'Boston', true, true, 'both', false),
  ('af000000-0000-4000-8000-000000000002', null, 'MSPCA-Angell', 'One of the oldest and largest animal welfare organizations in the country, running shelters, adoption centers, and a Humane Education Department across Massachusetts.', 'https://www.mspca.org', 'https://www.google.com/s2/favicons?domain=www.mspca.org&sz=128', 'animals', array['recurring'], false, false, 16, 'United States', 'MA', 'Boston', true, true, 'ongoing', false),
  ('af000000-0000-4000-8000-000000000003', null, 'Charles River Conservancy', 'A nonprofit working to restore and improve the parks along the Charles River, coordinating around 2,000 volunteers a year for hands-on park maintenance.', 'https://thecharles.org', 'https://www.google.com/s2/favicons?domain=thecharles.org&sz=128', 'environment', array['outdoors', 'family friendly', 'good for crews'], false, false, 0, 'United States', 'MA', 'Boston', true, true, 'both', false),
  ('af000000-0000-4000-8000-000000000004', null, 'Emerald Necklace Conservancy', 'The nonprofit steward of Boston historic Emerald Necklace park system, a chain of parks designed by Frederick Law Olmsted running through the city.', 'https://www.emeraldnecklace.org', 'https://www.google.com/s2/favicons?domain=www.emeraldnecklace.org&sz=128', 'environment', array['outdoors', 'family friendly'], false, false, 0, 'United States', 'MA', 'Boston', true, true, 'both', false),
  ('af000000-0000-4000-8000-000000000005', null, 'Massachusetts Department of Conservation and Recreation', 'The state agency managing parks, forests, and beaches across Massachusetts, running the Volunteers in the Parks program to support park stewardship statewide.', 'https://www.mass.gov', 'https://www.google.com/s2/favicons?domain=www.mass.gov&sz=128', 'environment', array['outdoors', 'family friendly'], false, false, 0, 'United States', 'MA', 'Boston', true, true, 'both', false),
  ('af000000-0000-4000-8000-000000000006', null, 'Special Olympics Massachusetts', 'The Massachusetts chapter of Special Olympics, providing year-round sports training and competition for athletes with intellectual disabilities statewide.', 'https://www.specialolympicsma.org', 'https://www.google.com/s2/favicons?domain=www.specialolympicsma.org&sz=128', 'sports', array['recurring', 'leadership role'], false, false, 15, 'United States', 'MA', 'Boston', true, true, 'both', false),
  ('af000000-0000-4000-8000-000000000007', null, 'Boston Children''s Hospital', 'One of the top pediatric hospitals in the world, running teen and college volunteer programs alongside its inpatient and clinic volunteer services.', 'https://www.childrenshospital.org', 'https://www.google.com/s2/favicons?domain=www.childrenshospital.org&sz=128', 'medicine', array['counts for school hours'], false, false, 16, 'United States', 'MA', 'Boston', true, true, 'ongoing', false),
  ('af000000-0000-4000-8000-000000000008', null, 'Boys and Girls Clubs of Boston', 'A youth development organization running clubs across Boston focused on healthy lifestyles, academic success, and leadership development for kids and teens.', 'https://www.bgcb.org', 'https://www.google.com/s2/favicons?domain=www.bgcb.org&sz=128', 'community', array['recurring', 'leadership role'], false, false, 14, 'United States', 'MA', 'Boston', true, true, 'ongoing', false)
on conflict (id) do nothing;

insert into public.opportunities
  (id, org_id, title, category, description, tags, min_age, remote, is_online, is_ongoing,
   hours_estimate, signup_link, external_url, starts_at, city, state)
values
  ('b0000000-0000-4000-8000-000000000001', 'af000000-0000-4000-8000-000000000001', 'Volunteer at the Greater Boston Food Bank', 'food', 'Individual and group volunteer shifts run Monday through Saturday, with every shift starting with a quick orientation covering food and warehouse safety. Weekday shifts fill up months in advance, so it helps to book early through the online volunteer form.', array['good for crews'], 12, false, false, true, '2-3 hrs', 'https://www.gbfb.org/get-involved/volunteer/', 'https://www.gbfb.org/get-involved/volunteer/', '2026-01-01T00:00:00Z', 'Boston', 'MA'),
  ('b0000000-0000-4000-8000-000000000002', 'af000000-0000-4000-8000-000000000002', 'Volunteer with MSPCA-Angell', 'animals', 'Volunteers 16 and up commit a few hours weekly to reception, dog care, or cat care at MSPCA locations, while younger teens can get involved through the Humane Education Department at Nevins Farm. It is one of the most established animal welfare programs in the Boston area.', array['recurring'], 16, false, false, true, '2-3 hrs / week', 'https://www.mspca.org/get-involved/volunteer/', 'https://www.mspca.org/get-involved/volunteer/', '2026-01-01T00:00:00Z', 'Boston', 'MA'),
  ('b0000000-0000-4000-8000-000000000003', 'af000000-0000-4000-8000-000000000003', 'Volunteer with the Charles River Conservancy', 'environment', 'Volunteers help maintain and restore the urban park system along the Charles River, with events that let you get outside and learn about the river while giving back. It is a great option if you want a scenic, recurring outdoor project.', array['outdoors', 'family friendly', 'good for crews'], 0, false, false, true, '2-3 hrs', 'https://thecharles.org/volunteer/', 'https://thecharles.org/volunteer/', '2026-01-01T00:00:00Z', 'Boston', 'MA'),
  ('b0000000-0000-4000-8000-000000000004', 'af000000-0000-4000-8000-000000000004', 'Volunteer with the Emerald Necklace Conservancy', 'environment', 'Hands-on projects include litter cleanups, invasive plant removal, plantings, and other ecological restoration work across the Emerald Necklace parks. It is a good pick if you are interested in landscape history along with hands-on conservation.', array['outdoors', 'family friendly'], 0, false, false, true, '2-3 hrs', 'https://www.emeraldnecklace.org/volunteer/', 'https://www.emeraldnecklace.org/volunteer/', '2026-01-01T00:00:00Z', 'Boston', 'MA'),
  ('b0000000-0000-4000-8000-000000000005', 'af000000-0000-4000-8000-000000000005', 'Join Volunteers in the Parks', 'environment', 'Volunteers support state park maintenance, trail work, and stewardship projects across the Massachusetts DCR park system, including many sites in and around Boston. It is a solid option if you want to help state parks specifically rather than city-run ones.', array['outdoors', 'family friendly'], 0, false, false, true, '2-3 hrs', 'https://www.mass.gov/info-details/volunteers-in-the-parks', 'https://www.mass.gov/info-details/volunteers-in-the-parks', '2026-01-01T00:00:00Z', 'Boston', 'MA'),
  ('b0000000-0000-4000-8000-000000000006', 'af000000-0000-4000-8000-000000000006', 'Volunteer with Special Olympics Massachusetts', 'sports', 'Volunteers help athletes with intellectual disabilities train and compete across a wide range of sports throughout the year, with roles from coaching to event-day support. It is a rewarding option whether you want a big season-long commitment or a single event day.', array['recurring', 'leadership role'], 15, false, false, true, '1-2 hrs / week', 'https://www.specialolympicsma.org/volunteer/ways-to-volunteer/find-volunteer-opportunities-near-you', 'https://www.specialolympicsma.org/volunteer/ways-to-volunteer/find-volunteer-opportunities-near-you', '2026-01-01T00:00:00Z', 'Boston', 'MA'),
  ('b0000000-0000-4000-8000-000000000007', 'af000000-0000-4000-8000-000000000007', 'Volunteer at Boston Children''s Hospital', 'medicine', 'Volunteers interact with patients, siblings, and families at the bedside, in playrooms, or in waiting areas, with a dedicated Summer Teen Program available for high schoolers. It is a strong pick if you are considering pediatric medicine as a career.', array['counts for school hours'], 16, false, false, true, 'Varies', 'https://www.childrenshospital.org/ways-help/volunteer-services/volunteer-opportunities-boston', 'https://www.childrenshospital.org/ways-help/volunteer-services/volunteer-opportunities-boston', '2026-01-01T00:00:00Z', 'Boston', 'MA'),
  ('b0000000-0000-4000-8000-000000000008', 'af000000-0000-4000-8000-000000000008', 'Volunteer with Boys and Girls Clubs of Boston', 'community', 'Volunteers work directly with youth on homework help, artistic skills, sports coaching, or general mentoring, sharing whatever skills or passions they bring. It is a good option if you want variety in how you give back, not just one fixed activity.', array['recurring', 'leadership role'], 14, false, false, true, '1-2 hrs / week', 'https://www.bgcb.org/get-involved/volunteer/', 'https://www.bgcb.org/get-involved/volunteer/', '2026-01-01T00:00:00Z', 'Boston', 'MA')
on conflict (id) do nothing;
