-- Migration 007: expand the directory with 24 more real organizations
-- (national + genuinely international programs), on top of the 25 already
-- seeded by migration 006. Pure inserts with fixed ids - safe to re-run
-- (on conflict does nothing, existing 25 orgs are untouched).

insert into public.organizations
  (id, owner_id, name, description, website, logo_url, category, tags, remote, international,
   min_age, country, state, city, verified, counts_for_service_hours, commitment_type, featured)
values
  ('f7000000-0000-4000-8000-000000000001', null, 'NASA Citizen Science', 'A collection of real NASA research projects that anyone in the world can contribute to online, from hunting exoplanets to tracking clouds and landslides.', 'https://science.nasa.gov', 'https://www.google.com/s2/favicons?domain=science.nasa.gov&sz=128', 'tech', array['no experience needed', 'one-time'], true, true, 0, 'Global', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000002', null, 'Cards for Hospitalized Kids', 'A volunteer network that makes and mails handmade cards to children in hospitals across the country, brightening long stays with a little bit of color and kindness.', 'https://www.cardsforhospitalizedkids.com', 'https://www.google.com/s2/favicons?domain=www.cardsforhospitalizedkids.com&sz=128', 'community', array['no experience needed', 'creative work', 'family friendly', 'counts for school hours'], true, false, 0, 'United States', null, null, true, true, 'one-time', false),
  ('f7000000-0000-4000-8000-000000000003', null, 'Letters Against Isolation', 'A grassroots letter-writing movement connecting volunteers worldwide with isolated seniors in care facilities, started to fight loneliness among older adults.', 'https://www.lettersagainstisolation.com', 'https://www.google.com/s2/favicons?domain=www.lettersagainstisolation.com&sz=128', 'seniors', array['no experience needed', 'creative work', 'family friendly'], true, true, 0, 'Global', null, null, true, true, 'one-time', false),
  ('f7000000-0000-4000-8000-000000000004', null, 'Love For Our Elders', 'An international letter and card campaign connecting volunteers with elderly people in care homes who receive few or no visitors.', 'https://loveforourelders.org', 'https://www.google.com/s2/favicons?domain=loveforourelders.org&sz=128', 'seniors', array['no experience needed', 'creative work', 'family friendly'], true, true, 0, 'Global', null, null, true, true, 'one-time', false),
  ('f7000000-0000-4000-8000-000000000005', null, 'TeensGive', 'A tutoring nonprofit built specifically for high schoolers, pairing teen volunteers with elementary students at Title 1 schools for virtual academic support.', 'https://teensgive.org', 'https://www.google.com/s2/favicons?domain=teensgive.org&sz=128', 'education', array['recurring', 'counts for school hours'], true, false, 14, 'United States', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000006', null, 'Missing Maps', 'A collaborative humanitarian mapping project where volunteers trace roads and buildings on satellite imagery so aid groups can reach communities that are not yet mapped.', 'https://www.missingmaps.org', 'https://www.google.com/s2/favicons?domain=www.missingmaps.org&sz=128', 'tech', array['no experience needed', 'one-time'], true, true, 13, 'Global', null, null, true, true, 'one-time', false),
  ('f7000000-0000-4000-8000-000000000007', null, 'TED Translators', 'A volunteer network of tens of thousands of translators who subtitle TED Talks into more than 100 languages so ideas can cross language barriers.', 'https://www.ted.com', 'https://www.google.com/s2/favicons?domain=www.ted.com&sz=128', 'education', array['creative work', 'one-time'], true, true, 14, 'Global', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000008', null, 'Distributed Proofreaders', 'The volunteer proofreading engine behind Project Gutenberg, the world largest free digital library, turning scanned pages into clean, searchable e-books.', 'https://www.pgdp.net', 'https://www.google.com/s2/favicons?domain=www.pgdp.net&sz=128', 'education', array['no experience needed', 'creative work', 'one-time'], true, true, 13, 'Global', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000009', null, 'LibriVox', 'A volunteer project recording free public-domain audiobooks, giving anyone in the world access to literature they might not otherwise be able to afford or find in audio form.', 'https://librivox.org', 'https://www.google.com/s2/favicons?domain=librivox.org&sz=128', 'art', array['creative work', 'one-time'], true, true, 13, 'Global', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000010', null, 'Mapping Prejudice', 'A research project that transcribes historical property deeds to uncover racially restrictive housing covenants and document a hidden part of American housing history.', 'https://mappingprejudice.umn.edu', 'https://www.google.com/s2/favicons?domain=mappingprejudice.umn.edu&sz=128', 'community', array['no experience needed', 'one-time'], true, false, 14, 'United States', null, null, true, true, 'one-time', false),
  ('f7000000-0000-4000-8000-000000000011', null, 'Sierra Club', 'One of the oldest and largest grassroots environmental organizations in the country, running campaigns to protect wild places and fight climate change.', 'https://www.sierraclub.org', 'https://www.google.com/s2/favicons?domain=www.sierraclub.org&sz=128', 'environment', array['recurring'], true, false, 14, 'United States', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000012', null, 'Youth Volunteer Corps', 'A national program that organizes team-based service projects specifically for youth ages 11 to 18, letting kids serve together without parents needing to supervise.', 'https://www.yvc.org', 'https://www.google.com/s2/favicons?domain=www.yvc.org&sz=128', 'community', array['good for crews', 'counts for school hours'], false, false, 11, 'United States', null, null, true, true, 'both', false),
  ('f7000000-0000-4000-8000-000000000013', null, 'ScholarMatch', 'A nonprofit that pairs volunteer coaches with underserved students to guide them through college applications, financial aid, and the transition to campus.', 'https://scholarmatch.org', 'https://www.google.com/s2/favicons?domain=scholarmatch.org&sz=128', 'education', array['recurring', 'leadership role'], true, false, 18, 'United States', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000014', null, 'Kids That Do Good', 'A directory and community built by young people, for young people and families, to find existing charities to plug into or get support starting their own service project.', 'https://kidsthatdogood.com', 'https://www.google.com/s2/favicons?domain=kidsthatdogood.com&sz=128', 'community', array['no experience needed', 'family friendly'], true, true, 0, 'Global', null, null, true, true, 'both', false),
  ('f7000000-0000-4000-8000-000000000015', null, 'Peace Corps', 'A United States government agency that sends volunteers to live and work in communities abroad for two-year assignments in education, health, agriculture, and more.', 'https://www.peacecorps.gov', 'https://www.google.com/s2/favicons?domain=www.peacecorps.gov&sz=128', 'community', array['leadership role', 'recurring'], false, true, 18, 'Global', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000016', null, 'AmeriCorps', 'The federal agency that places thousands of Americans into full- or part-time national service positions each year, tackling poverty, disaster response, education, and health.', 'https://americorps.gov', 'https://www.google.com/s2/favicons?domain=americorps.gov&sz=128', 'community', array['leadership role', 'recurring'], false, false, 17, 'United States', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000017', null, 'Boys & Girls Clubs of America', 'A national network of local clubs providing after-school programs, mentoring, and activities for young people, staffed heavily by community volunteers.', 'https://www.bgca.org', 'https://www.google.com/s2/favicons?domain=www.bgca.org&sz=128', 'education', array['recurring', 'counts for school hours'], false, false, 16, 'United States', null, null, true, true, 'both', false),
  ('f7000000-0000-4000-8000-000000000018', null, 'Big Brothers Big Sisters of America', 'The largest youth mentoring network in the country, matching adult volunteers ("Bigs") in one-to-one friendships with young people ("Littles") who could benefit from an additional mentor.', 'https://www.bbbs.org', 'https://www.google.com/s2/favicons?domain=www.bbbs.org&sz=128', 'community', array['leadership role', 'recurring'], false, false, 18, 'United States', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000019', null, 'American Cancer Society', 'The nation largest voluntary health organization fighting cancer through research funding, patient support, and community fundraising events like Relay For Life.', 'https://www.cancer.org', 'https://www.google.com/s2/favicons?domain=www.cancer.org&sz=128', 'medicine', array['good for crews', 'counts for school hours'], false, false, 13, 'United States', null, null, true, true, 'both', false),
  ('f7000000-0000-4000-8000-000000000020', null, 'World Central Kitchen', 'A disaster relief organization founded by chef Jose Andres that shows up after hurricanes, earthquakes, and other crises to cook and serve fresh meals to affected communities worldwide.', 'https://wck.org', 'https://www.google.com/s2/favicons?domain=wck.org&sz=128', 'disaster', array['physical work', 'good for crews'], false, true, 18, 'Global', null, null, true, true, 'one-time', false),
  ('f7000000-0000-4000-8000-000000000021', null, 'The Nature Conservancy', 'One of the largest environmental nonprofits in the world, working to protect land and water through conservation projects run by local chapters.', 'https://www.nature.org', 'https://www.google.com/s2/favicons?domain=www.nature.org&sz=128', 'environment', array['outdoors', 'physical work'], false, false, 16, 'United States', null, null, true, true, 'both', false),
  ('f7000000-0000-4000-8000-000000000022', null, 'UNICEF USA', 'The U.S. arm of the United Nations agency dedicated to child welfare worldwide, running student clubs and advocacy campaigns alongside its global relief work.', 'https://www.unicefusa.org', 'https://www.google.com/s2/favicons?domain=www.unicefusa.org&sz=128', 'community', array['leadership role', 'recurring'], true, true, 13, 'Global', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000023', null, 'Amnesty International', 'A global human rights movement with millions of members and supporters, campaigning against injustice through research, advocacy, and grassroots action.', 'https://www.amnesty.org', 'https://www.google.com/s2/favicons?domain=www.amnesty.org&sz=128', 'community', array['leadership role', 'recurring'], true, true, 13, 'Global', null, null, true, true, 'ongoing', false),
  ('f7000000-0000-4000-8000-000000000024', null, 'Ocean Conservancy', 'The organizer of the International Coastal Cleanup, the world largest volunteer effort for ocean health, coordinating beach and waterway cleanups in more than 100 countries every year.', 'https://oceanconservancy.org', 'https://www.google.com/s2/favicons?domain=oceanconservancy.org&sz=128', 'environment', array['good for crews', 'outdoors', 'family friendly'], false, true, 0, 'Global', null, null, true, true, 'one-time', false)
on conflict (id) do nothing;

insert into public.opportunities
  (id, org_id, title, category, description, tags, min_age, remote, is_online, is_ongoing,
   hours_estimate, signup_link, external_url, starts_at, city, state)
values
  ('f8000000-0000-4000-8000-000000000001', 'f7000000-0000-4000-8000-000000000001', 'Do Real NASA Science From Home', 'tech', 'Dozens of active NASA projects need human eyes to spot patterns computers miss - classifying craters on Mars, tagging clouds for climate research, or helping track landslides after storms. Most tasks take just a few minutes and come with short tutorials, so no science background is required. It is one of the few ways a student anywhere in the world can say they contributed to an actual NASA dataset.', array['no experience needed', 'one-time'], 0, true, true, true, 'Flexible', 'https://science.nasa.gov/citizen-science/', 'https://science.nasa.gov/citizen-science/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000002', 'f7000000-0000-4000-8000-000000000002', 'Make Cards for Hospitalized Kids', 'community', 'Every card you make gets delivered to a real child spending time in a hospital, and the organization is set up so people of any age can take part with a parent if needed. It works with hour-tracking services like MobileServe and X2VOL and is a certified President Volunteer Service Award partner, so hours can be documented for school or scholarship applications. It is one of the simplest, most flexible ways to log service time from your kitchen table.', array['no experience needed', 'creative work', 'family friendly', 'counts for school hours'], 0, true, true, true, '1-2 hrs', 'https://www.cardsforhospitalizedkids.com/', 'https://www.cardsforhospitalizedkids.com/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000003', 'f7000000-0000-4000-8000-000000000003', 'Write Letters to Isolated Seniors', 'seniors', 'Loneliness is one of the biggest quality-of-life issues for seniors in long-term care, and a handwritten letter can be a genuine highlight of someone week. Volunteers sign up online, get mailing information for a facility, and write as many or as few letters as they want on their own schedule. It costs nothing but a stamp and a few minutes, and it works the same whether you live down the street or across the world.', array['no experience needed', 'creative work', 'family friendly'], 0, true, true, true, '30 min', 'https://www.lettersagainstisolation.com/', 'https://www.lettersagainstisolation.com/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000004', 'f7000000-0000-4000-8000-000000000004', 'Send Cheer to Elders Worldwide', 'seniors', 'Love For Our Elders runs regular themed letter-writing campaigns (holidays, birthdays, just-because) and ships volunteer letters directly to partner care homes. Because everything happens by mail, volunteers anywhere in the world can join, and there is no minimum commitment beyond writing when a campaign is open. It is a favorite for younger volunteers and families doing service projects together.', array['no experience needed', 'creative work', 'family friendly'], 0, true, true, true, '30 min', 'https://loveforourelders.org/', 'https://loveforourelders.org/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000005', 'f7000000-0000-4000-8000-000000000005', 'Tutor Elementary Students as a Teen', 'education', 'TeensGive was founded by high schoolers for high schoolers, so the entire program - training, scheduling, and support - is designed around a student volunteer schedule. You get matched with a younger student at a Title 1 school and meet virtually for regular sessions in reading, writing, or math. It is a strong pick if you want a real mentoring relationship (not just one-off tasks) and consistent, verifiable hours over a semester.', array['recurring', 'counts for school hours'], 14, true, true, true, '1 hr / week', 'https://teensgive.org/', 'https://teensgive.org/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000006', 'f7000000-0000-4000-8000-000000000006', 'Map Communities for Disaster Relief', 'tech', 'Large parts of the world are still missing from digital maps, which makes it hard for aid organizations to plan vaccine campaigns, disaster response, or emergency routes. Missing Maps runs remote "mapathons" where volunteers trace buildings and roads from satellite photos directly into OpenStreetMap, no experience or special software knowledge needed beyond a short tutorial. Every trace you add can genuinely speed up a real relief effort somewhere in the world.', array['no experience needed', 'one-time'], 13, true, true, true, 'Flexible', 'https://www.missingmaps.org/', 'https://www.missingmaps.org/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000007', 'f7000000-0000-4000-8000-000000000007', 'Subtitle TED Talks', 'education', 'If you are fluent in a second language, you can pick a talk you find genuinely interesting and translate or transcribe its subtitles at your own pace using TED free online tools. Your name goes into the credits, and the work is reviewed by other volunteers before it goes live, so quality and accuracy matter more than speed. It is a great long-term project for language learners who want a portfolio of real, published translation work.', array['creative work', 'one-time'], 14, true, true, true, 'Flexible', 'https://www.ted.com/participate/translate', 'https://www.ted.com/participate/translate', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000008', 'f7000000-0000-4000-8000-000000000008', 'Proofread Books for Project Gutenberg', 'education', 'Every free e-book on Project Gutenberg passed through several rounds of volunteer proofreading to fix scanning errors and preserve formatting, and anyone can join a round after a short registration and a practice page. You work one page at a time, so a single ten-minute session leaves the book better than you found it, with no obligation to finish anything. It is especially good for volunteers who love reading, editing, or old books.', array['no experience needed', 'creative work', 'one-time'], 13, true, true, true, 'Flexible', 'https://www.pgdp.net/', 'https://www.pgdp.net/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000009', 'f7000000-0000-4000-8000-000000000009', 'Record a Chapter as an Audiobook', 'art', 'LibriVox splits public-domain books into short sections so volunteers can record just one chapter using a phone or basic microphone, then a coordinator handles the technical assembly into a finished audiobook. Your reading gets credited by name and becomes part of a permanent, free library that anyone can stream or download. It is a fun option for volunteers who like performing, reading aloud, or want a creative project that leaves something lasting online.', array['creative work', 'one-time'], 13, true, true, true, '1-2 hrs', 'https://librivox.org/', 'https://librivox.org/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000010', 'f7000000-0000-4000-8000-000000000010', 'Transcribe Historical Housing Records', 'community', 'Racially restrictive covenants shaped where people could and could not buy homes for decades, but that history is often buried in millions of old handwritten property records. Volunteers transcribe scanned deed records online in short, guided sessions, and the resulting data is used by researchers, journalists, and city planners to understand and address housing inequity. No background in history or law is needed, just patience and attention to detail.', array['no experience needed', 'one-time'], 14, true, true, true, 'Flexible', 'https://mappingprejudice.umn.edu/', 'https://mappingprejudice.umn.edu/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000011', 'f7000000-0000-4000-8000-000000000011', 'Join an Environmental Justice Campaign', 'environment', 'Sierra Club campaigns combine local organizing with digital action, so student volunteers can contact decision-makers, help plan events, and spread the word about issues like clean energy and public lands protection largely online. Many chapters also welcome teens to in-person outings and cleanups if you want a hands-on component. It is a solid pick if you care about environmental policy specifically, not just cleanups.', array['recurring'], 14, true, true, true, 'Flexible', 'https://www.sierraclub.org/take-action', 'https://www.sierraclub.org/take-action', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000012', 'f7000000-0000-4000-8000-000000000012', 'Join a Youth Service Team', 'community', 'YVC exists because most volunteer programs are built for adults, so it designs every project - park cleanups, food sorting, senior support - to be led by trained staff for groups of young people working together. Projects typically run a few hours on a weekend and are a great option for students who want the social, team feeling of volunteering with peers their own age. Local chapters vary, so check yvc.org to find one near you.', array['good for crews', 'counts for school hours'], 11, false, false, true, '2-3 hrs', 'https://www.yvc.org/', 'https://www.yvc.org/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000013', 'f7000000-0000-4000-8000-000000000013', 'Coach a Student Through College Applications', 'education', 'ScholarMatch coaches meet regularly over video with a student who is often the first in their family to apply to college, helping with everything from essay brainstorming to understanding financial aid offers. It is a meaningful fit for college students or recent grads who remember the process well and want to give back in a structured, ongoing way rather than a one-off task. Training and matching are handled by ScholarMatch staff.', array['recurring', 'leadership role'], 18, true, true, true, '1-2 hrs / week', 'https://scholarmatch.org/', 'https://scholarmatch.org/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000014', 'f7000000-0000-4000-8000-000000000014', 'Find or Start a Kid-Led Service Project', 'community', 'Kids That Do Good was built by a young founder who wanted an easier on-ramp for other kids and teens who want to help but do not know where to start. The site lists ideas and existing charities sorted by interest, and also has guidance for starting your own small project, like a supply drive or neighborhood cleanup, and tracking your own impact. It is especially useful for younger volunteers and families looking for a first project.', array['no experience needed', 'family friendly'], 0, true, true, true, 'Flexible', 'https://kidsthatdogood.com/', 'https://kidsthatdogood.com/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000015', 'f7000000-0000-4000-8000-000000000015', 'Serve Abroad for Two Years', 'community', 'Peace Corps volunteers live in the community they serve, usually learning the local language, and work on projects identified by that community itself rather than projects designed from outside. It is a serious, multi-year commitment intended for adults (18+), often after finishing a degree, so this is one to bookmark for later rather than a quick weekend project. Application and country placement are handled entirely through the official Peace Corps site.', array['leadership role', 'recurring'], 18, false, false, true, '2-year term', 'https://www.peacecorps.gov/volunteer/', 'https://www.peacecorps.gov/volunteer/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000016', 'f7000000-0000-4000-8000-000000000016', 'Serve Your Community Through AmeriCorps', 'community', 'AmeriCorps members take on structured, term-length service positions (often 10-12 months) with local nonprofits, schools, or disaster relief teams, usually receiving a modest living stipend and sometimes an education award at the end. Many programs accept applicants as young as 17 with a guardian sponsor, though most members are college-age or older. It is a strong option for someone ready to commit a school year or a gap year to full-time service.', array['leadership role', 'recurring'], 17, false, false, true, 'Term-based', 'https://americorps.gov/serve', 'https://americorps.gov/serve', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000017', 'f7000000-0000-4000-8000-000000000017', 'Volunteer at a Local Boys & Girls Club', 'education', 'Local clubs need help running homework help, sports, art projects, and mentoring programs for kids after school, and teen volunteers are often welcomed as junior staff or program helpers. Because BGCA is a network of independently run local clubs, the exact role, schedule, and minimum age can vary, so the official volunteer page routes you to your nearest club to apply directly. It is a good option if you enjoy working with younger kids in person.', array['recurring', 'counts for school hours'], 16, false, false, true, '2-3 hrs / week', 'https://www.bgca.org/volunteer', 'https://www.bgca.org/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000018', 'f7000000-0000-4000-8000-000000000018', 'Become a Mentor', 'community', 'A Big commits to spending a few hours a month with their matched Little doing everyday activities - homework, sports, just hanging out - building a consistent, caring relationship over at least a year. Because it involves an ongoing one-on-one relationship with a minor, mentors must be adults (18+) and go through a background check and interview process. It is worth bookmarking for college or after graduation if you want deep, long-term mentoring impact.', array['leadership role', 'recurring'], 18, false, false, true, '2-4 hrs / month', 'https://www.bbbs.org/get-involved/', 'https://www.bbbs.org/get-involved/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000019', 'f7000000-0000-4000-8000-000000000019', 'Volunteer at a Cancer Society Event', 'medicine', 'Most student volunteers get involved through events like Relay For Life or Making Strides Against Breast Cancer, helping with setup, registration, and cheering on participants, or by starting a team at their school. There are also year-round roles supporting patients directly, such as driving patients to treatment (18+) or staffing a local office. It is a flexible option if you want either a single big event or an ongoing role.', array['good for crews', 'counts for school hours'], 13, false, false, true, 'Half day', 'https://www.cancer.org/involved.html', 'https://www.cancer.org/involved.html', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000020', 'f7000000-0000-4000-8000-000000000020', 'Deploy for Disaster Relief Cooking', 'disaster', 'When a disaster strikes, World Central Kitchen activates local restaurants and kitchens and calls in volunteers to help cook and distribute thousands of meals a day, sometimes within hours of an event. Because deployments are physically demanding and often happen in disaster zones, volunteer roles are generally for adults who can commit to being on-site, though the organization also relies on local community volunteers wherever it operates. Sign up through their site to be notified when help is needed near you.', array['physical work', 'good for crews'], 18, false, false, true, 'Full day', 'https://wck.org/volunteer', 'https://wck.org/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000021', 'f7000000-0000-4000-8000-000000000021', 'Volunteer with a Local Nature Conservancy Chapter', 'environment', 'Local chapters run hands-on projects like invasive species removal, trail maintenance, prairie burns, and citizen science surveys on protected land, usually a few times a month during the season. Volunteer opportunities and minimum ages vary a lot by state chapter, so the official site routes you to sign-ups for the preserves nearest you. It is a strong choice if you love being outdoors and want real conservation experience.', array['outdoors', 'physical work'], 16, false, false, true, 'Half day', 'https://www.nature.org/en-us/get-involved/how-to-help/volunteer/', 'https://www.nature.org/en-us/get-involved/how-to-help/volunteer/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000022', 'f7000000-0000-4000-8000-000000000022', 'Start or Join a UNICEF Club', 'community', 'UNICEF Clubs let middle and high school students run awareness campaigns, fundraisers, and advocacy projects at their own school with toolkits and support from UNICEF USA staff. Because everything is organized through your own club, the time commitment is entirely up to your group, and it looks great alongside leadership experience if you help start one. It pairs well with a global cause if you want your local effort connected to a large-scale humanitarian organization.', array['leadership role', 'recurring'], 13, true, true, true, 'Flexible', 'https://www.unicefusa.org/volunteer', 'https://www.unicefusa.org/volunteer', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000023', 'f7000000-0000-4000-8000-000000000023', 'Join a Student Human Rights Group', 'community', 'Amnesty youth and student groups organize letter-writing campaigns for prisoners of conscience, run awareness events, and take action on current human rights issues, often meeting through a school or community chapter. Because Amnesty operates through country-level sections, the exact way to get involved depends on where you live, so the global site routes you to your local section. It is a good match if human rights and civic advocacy are specifically what draw you to service.', array['leadership role', 'recurring'], 13, true, true, true, 'Flexible', 'https://www.amnesty.org/en/get-involved/', 'https://www.amnesty.org/en/get-involved/', '2026-01-01T00:00:00Z', null, null),
  ('f8000000-0000-4000-8000-000000000024', 'f7000000-0000-4000-8000-000000000024', 'Join or Start a Coastal Cleanup', 'environment', 'Every year, millions of volunteers around the world join a coastal or waterway cleanup as part of this single coordinated event, logging exactly what kind of trash they collect so it can feed real ocean-health research. You can join an existing cleanup near you through the official site map, or register to organize your own if there is not one nearby yet. It is family friendly, works for any age with supervision, and is one of the most visibly global service projects a student can point to.', array['good for crews', 'outdoors', 'family friendly'], 0, false, false, true, '2-3 hrs', 'https://oceanconservancy.org/trash-free-seas/international-coastal-cleanup/', 'https://oceanconservancy.org/trash-free-seas/international-coastal-cleanup/', '2026-01-01T00:00:00Z', null, null)
on conflict (id) do nothing;

-- Real photos verified from each org's own site (most sites block automated
-- fetches, so only these two came back with a confirmed, working image URL).
-- The rest fall back to the category hero banner already shipped in the app.
update public.organizations set image_url = 'https://d21y75miwcfqoq.cloudfront.net/316387c9'
  where website = 'https://www.feedingamerica.org';
update public.organizations set image_url = 'https://images.squarespace-cdn.com/content/v1/57c0d8d1e58c622e8b6d5328/c74646d9-694c-4af5-8993-c6963a302288/UPchieve+online+tutoring+homepage.png'
  where website = 'https://upchieve.org';
