-- Migration 036: 50 more real, local Georgia organizations across a broad mix of
-- categories (food, animals, music, tech, faith, disaster, environment, seniors,
-- education, gardening, community, medicine, sports, veterans) and cities beyond
-- Atlanta (Savannah, Augusta, Columbus, Macon, Athens, Gainesville, Roswell,
-- Marietta, Decatur, and more). Each org was researched individually and its
-- website/volunteer page verified. Pure inserts with fixed ids - safe to re-run,
-- existing rows untouched. Complements migration-008 (the first 24 GA orgs).

insert into public.organizations
  (id, owner_id, name, description, website, logo_url, category, tags, remote, international,
   min_age, country, state, city, verified, counts_for_service_hours, commitment_type, featured)
values
  -- FOOD
  -- NOTE: 'Atlanta Community Food Bank' (was c1...001) removed - it duplicated an
  -- existing directory org (e5...024); see migration-042-dedupe-036.sql.
  ('c1000000-0000-4000-8000-000000000002', null, 'Second Helpings Atlanta', 'A food-rescue nonprofit whose volunteers use their own vehicles to pick up surplus fresh food from grocers and restaurants and deliver it to shelters, pantries, and after-school programs across metro Atlanta.', 'https://secondhelpingsatlanta.org', 'https://www.google.com/s2/favicons?domain=secondhelpingsatlanta.org&sz=128', 'food', array['good for crews', 'recurring'], false, false, 14, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000003', null, 'Open Hand Atlanta', 'A nonprofit that cooks and delivers medically tailored meals to seniors and people managing chronic illness across metro Atlanta, relying on volunteers in the kitchen and on delivery routes.', 'https://www.openhandatlanta.org', 'https://www.google.com/s2/favicons?domain=www.openhandatlanta.org&sz=128', 'food', array['recurring', 'good for crews'], false, false, 13, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000004', null, 'Golden Harvest Food Bank', 'The regional food bank for the Augusta area and the Central Savannah River region, distributing millions of meals a year through a network of pantries and a Master''s Table soup kitchen.', 'https://www.goldenharvest.org', 'https://www.google.com/s2/favicons?domain=www.goldenharvest.org&sz=128', 'food', array['good for crews', 'family friendly'], false, false, 12, 'United States', 'GA', 'Augusta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000005', null, 'Feeding the Valley Food Bank', 'The food bank serving Columbus and the Chattahoochee Valley region of west Georgia, receiving and distributing donated food and fresh produce to partner agencies across many counties.', 'https://feedingthevalley.org', 'https://www.google.com/s2/favicons?domain=feedingthevalley.org&sz=128', 'food', array['good for crews', 'physical work'], false, false, 12, 'United States', 'GA', 'Columbus', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000006', null, 'Georgia Mountain Food Bank', 'A food bank in Gainesville serving Hall, Dawson, Forsyth, Lumpkin, and Union counties in north Georgia, distributing food to partner agencies and running a community garden.', 'https://www.gamountainfoodbank.org', 'https://www.google.com/s2/favicons?domain=www.gamountainfoodbank.org&sz=128', 'food', array['good for crews', 'family friendly'], false, false, 12, 'United States', 'GA', 'Gainesville', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000007', null, 'Urban Recipe', 'An Atlanta nonprofit built around food co-ops, where neighbors work together to pack and distribute roughly 40,000 pounds of groceries a month with dignity rather than a traditional pantry line.', 'https://urbanrecipe.org', 'https://www.google.com/s2/favicons?domain=urbanrecipe.org&sz=128', 'food', array['recurring', 'good for crews'], false, false, 12, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  -- ANIMALS
  ('c1000000-0000-4000-8000-000000000008', null, 'Atlanta Humane Society', 'One of the oldest and largest animal-welfare organizations in Georgia, caring for and rehoming thousands of dogs and cats each year across its metro Atlanta campuses.', 'https://atlantahumane.org', 'https://www.google.com/s2/favicons?domain=atlantahumane.org&sz=128', 'animals', array['recurring'], false, false, 16, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  -- NOTE: 'LifeLine Animal Project' (was c1...009) removed - it duplicated an
  -- existing directory org (e5...025); see migration-042-dedupe-036.sql.
  ('c1000000-0000-4000-8000-000000000010', null, 'Furkids', 'Georgia''s largest no-kill animal rescue and shelter organization, operating cat and dog shelters in metro Atlanta and welcoming youth volunteers alongside a parent for cat care and puppy socialization.', 'https://furkids.org', 'https://www.google.com/s2/favicons?domain=furkids.org&sz=128', 'animals', array['family friendly', 'recurring'], false, false, 13, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000011', null, 'PAWS Atlanta', 'One of metro Atlanta''s oldest no-kill shelters, based in Decatur, caring for homeless dogs and cats and relying on adult volunteers for daily animal care and events.', 'https://www.pawsatlanta.org', 'https://www.google.com/s2/favicons?domain=www.pawsatlanta.org&sz=128', 'animals', array['recurring'], false, false, 18, 'United States', 'GA', 'Decatur', true, true, 'ongoing', false),
  ('c1000000-0000-4000-8000-000000000012', null, 'Humane Society for Greater Savannah', 'A nonprofit shelter serving the Savannah area with adoption, foster, and community programs, offering hands-on and event volunteer roles for a range of ages.', 'https://www.humanesocietysav.org', 'https://www.google.com/s2/favicons?domain=www.humanesocietysav.org&sz=128', 'animals', array['recurring', 'family friendly'], false, false, 14, 'United States', 'GA', 'Savannah', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000013', null, 'AWARE Wildlife Center', 'A wildlife rehabilitation center on the edge of Atlanta''s Arabia Mountain that rescues, treats, and releases native Georgia wildlife and trains volunteers in animal care and habitat work.', 'https://awarewildlife.org', 'https://www.google.com/s2/favicons?domain=awarewildlife.org&sz=128', 'animals', array['outdoors', 'recurring'], false, false, 16, 'United States', 'GA', 'Lithonia', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000014', null, 'Coastal Pet Rescue', 'A Savannah-area rescue that finds homes for dogs and cats through a foster-based network and welcomes volunteers, including teens with parental permission through its CPR Teens program.', 'https://coastalpetrescue.org', 'https://www.google.com/s2/favicons?domain=coastalpetrescue.org&sz=128', 'animals', array['recurring', 'family friendly'], false, false, 14, 'United States', 'GA', 'Savannah', true, true, 'both', false),
  -- MUSIC
  ('c1000000-0000-4000-8000-000000000015', null, 'Atlanta Music Project', 'A nonprofit that provides intensive, tuition-free music education and performance training to young people in under-resourced Atlanta communities.', 'https://atlantamusicproject.org', 'https://www.google.com/s2/favicons?domain=atlantamusicproject.org&sz=128', 'music', array['recurring', 'creative work'], false, false, 14, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000016', null, 'Pianos for Peace', 'An Atlanta nonprofit that builds peace through music and education, placing painted street pianos around the city and delivering arts programs to schools, hospitals, and senior homes.', 'https://www.pianosforpeace.org', 'https://www.google.com/s2/favicons?domain=www.pianosforpeace.org&sz=128', 'music', array['creative work', 'good for crews'], false, false, 13, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000017', null, 'Henry For Music', 'A metro Atlanta 501(c)(3) that collects and gifts tuition-free instruments and music lessons to students who have the interest but not the means, powered by volunteer mentors and artists.', 'https://henryformusic.org', 'https://www.google.com/s2/favicons?domain=henryformusic.org&sz=128', 'music', array['creative work', 'recurring'], false, false, 14, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  -- TECH
  ('c1000000-0000-4000-8000-000000000018', null, 'TechBridge', 'An Atlanta nonprofit that brings affordable technology and business expertise to other nonprofits and runs a free technology career training program to help break the cycle of poverty.', 'https://techbridge.org', 'https://www.google.com/s2/favicons?domain=techbridge.org&sz=128', 'tech', array['recurring', 'leadership role'], false, false, 16, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000019', null, 'Bridge2Tech', 'A Georgia nonprofit offering free STEM, coding, and esports programs to at-risk and underserved youth, with volunteer roles mentoring students in technology skills.', 'https://www.bridge2tech.org', 'https://www.google.com/s2/favicons?domain=www.bridge2tech.org&sz=128', 'tech', array['recurring', 'leadership role', 'counts for school hours'], false, false, 13, 'United States', 'GA', 'Roswell', true, true, 'both', false),
  -- FAITH
  ('c1000000-0000-4000-8000-000000000020', null, 'Atlanta Habitat for Humanity', 'A Christian housing ministry that partners with families to build and repair affordable homes across Atlanta, engaging over 6,000 volunteers a year on build sites and in its ReStore.', 'https://atlantahabitat.org', 'https://www.google.com/s2/favicons?domain=atlantahabitat.org&sz=128', 'faith', array['good for crews', 'physical work', 'outdoors'], false, false, 16, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000021', null, 'Augusta Habitat for Humanity', 'A volunteer-driven affiliate of Habitat for Humanity serving the Augusta and CSRA region, building and rehabbing homes with skilled and unskilled volunteers alike.', 'https://augustahabitat.org', 'https://www.google.com/s2/favicons?domain=augustahabitat.org&sz=128', 'faith', array['good for crews', 'physical work', 'outdoors'], false, false, 16, 'United States', 'GA', 'Augusta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000022', null, 'Catholic Charities Atlanta', 'A faith-based social services agency serving people of all backgrounds across north Georgia with refugee resettlement, counseling, and family support programs, plus tutoring and mentoring volunteer roles.', 'https://catholiccharitiesatlanta.org', 'https://www.google.com/s2/favicons?domain=catholiccharitiesatlanta.org&sz=128', 'faith', array['recurring', 'counts for school hours'], false, false, 14, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000023', null, 'MUST Ministries', 'A faith-based nonprofit in Marietta serving people facing hunger and homelessness across Cobb, Cherokee, and surrounding counties through shelters, food pantries, and a summer lunch program for kids.', 'https://www.mustministries.org', 'https://www.google.com/s2/favicons?domain=www.mustministries.org&sz=128', 'faith', array['good for crews', 'family friendly', 'recurring'], false, false, 13, 'United States', 'GA', 'Marietta', true, true, 'both', false),
  -- DISASTER RELIEF
  ('c1000000-0000-4000-8000-000000000024', null, 'American Red Cross of Georgia', 'The Georgia region of the American Red Cross, where trained volunteers respond to home fires and larger disasters with food, shelter, and comfort and can deploy statewide or nationally.', 'https://www.redcross.org/local/georgia.html', 'https://www.google.com/s2/favicons?domain=www.redcross.org&sz=128', 'disaster', array['recurring', 'leadership role'], false, false, 16, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  -- ENVIRONMENT
  ('c1000000-0000-4000-8000-000000000025', null, 'Savannah Riverkeeper', 'A nonprofit advocacy organization protecting the Savannah River watershed through restoration, education, and dozens of river and community cleanups a year in Augusta, Savannah, and between.', 'https://www.savannahriverkeeper.org', 'https://www.google.com/s2/favicons?domain=www.savannahriverkeeper.org&sz=128', 'environment', array['outdoors', 'physical work', 'good for crews'], false, false, 12, 'United States', 'GA', 'Augusta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000026', null, 'Ogeechee Riverkeeper', 'A coastal Georgia nonprofit defending the Ogeechee, Canoochee, and coastal watersheds through water-quality monitoring, litter cleanups, and its Protect the Vernon project.', 'https://www.ogeecheeriverkeeper.org', 'https://www.google.com/s2/favicons?domain=www.ogeecheeriverkeeper.org&sz=128', 'environment', array['outdoors', 'physical work', 'good for crews'], false, false, 12, 'United States', 'GA', 'Savannah', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000027', null, 'Chattahoochee Riverkeeper', 'One of the country''s most effective river-protection groups, guarding the Chattahoochee - metro Atlanta''s main drinking-water source - through cleanups, water testing, and advocacy.', 'https://chattahoochee.org', 'https://www.google.com/s2/favicons?domain=chattahoochee.org&sz=128', 'environment', array['outdoors', 'physical work', 'good for crews'], false, false, 12, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000028', null, 'Chattahoochee Nature Center', 'A nonprofit nature center in Roswell along the Chattahoochee River offering wildlife, gardening, and education volunteer roles for teens and adults amid 127 acres of protected land.', 'https://www.chattnaturecenter.org', 'https://www.google.com/s2/favicons?domain=www.chattnaturecenter.org&sz=128', 'environment', array['outdoors', 'recurring', 'family friendly'], false, false, 12, 'United States', 'GA', 'Roswell', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000029', null, 'Georgia Adopt-A-Stream', 'A statewide program that trains volunteers to adopt and monitor a local stream, river, lake, or wetland, collecting real water-quality data that protects Georgia''s waterways.', 'https://adoptastream.georgia.gov', 'https://www.google.com/s2/favicons?domain=adoptastream.georgia.gov&sz=128', 'environment', array['outdoors', 'recurring', 'counts for school hours'], false, false, 12, 'United States', 'GA', 'Georgia', true, true, 'both', false),
  -- SENIORS
  ('c1000000-0000-4000-8000-000000000030', null, 'Senior Citizens Inc.', 'A Savannah nonprofit that has run Meals on Wheels of Coastal Georgia for decades, delivering meals and daily check-ins to homebound older adults across seven coastal counties.', 'https://seniorcitizensinc.org', 'https://www.google.com/s2/favicons?domain=seniorcitizensinc.org&sz=128', 'seniors', array['recurring'], false, false, 16, 'United States', 'GA', 'Savannah', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000031', null, 'Meals on Wheels of Middle Georgia', 'A nonprofit delivering hot meals and friendly visits to homebound seniors around Macon and middle Georgia, pairing nutrition with a daily safety check.', 'https://www.mowmidga.org', 'https://www.google.com/s2/favicons?domain=www.mowmidga.org&sz=128', 'seniors', array['recurring'], false, false, 16, 'United States', 'GA', 'Macon', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000032', null, 'Athens Community Council on Aging', 'An Athens nonprofit supporting older adults with meals, day programs, a community garden, and companionship, offering volunteer roles from meal delivery to garden work.', 'https://www.accaging.org', 'https://www.google.com/s2/favicons?domain=www.accaging.org&sz=128', 'seniors', array['recurring', 'outdoors'], false, false, 14, 'United States', 'GA', 'Athens', true, true, 'both', false),
  -- EDUCATION
  ('c1000000-0000-4000-8000-000000000033', null, 'Communities In Schools of Atlanta', 'The Atlanta affiliate of the nation''s largest dropout-prevention network, surrounding students with support through mentoring, reading coaching, and lunch-buddy programs inside schools.', 'https://www.cisatlanta.org', 'https://www.google.com/s2/favicons?domain=www.cisatlanta.org&sz=128', 'education', array['recurring', 'counts for school hours', 'leadership role'], false, false, 16, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000034', null, 'Horizons Atlanta', 'A nonprofit running six-week summer learning programs for students from under-resourced communities, closing the summer learning gap with the help of volunteer readers and classroom helpers.', 'https://horizonsatlanta.org', 'https://www.google.com/s2/favicons?domain=horizonsatlanta.org&sz=128', 'education', array['recurring', 'counts for school hours'], false, false, 14, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000035', null, 'Junior Achievement of Georgia', 'A nonprofit that sends volunteers into classrooms across Georgia to teach students about work readiness, entrepreneurship, and financial literacy through hands-on lessons.', 'https://www.georgia.ja.org', 'https://www.google.com/s2/favicons?domain=www.georgia.ja.org&sz=128', 'education', array['leadership role', 'counts for school hours'], false, false, 18, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000036', null, 'SAV Youth Mentoring Hub', 'A Savannah initiative that connects the community with vetted local youth-mentoring organizations, making it easy to find and apply to become a mentor to a young person.', 'https://savyouthmentoring.org', 'https://www.google.com/s2/favicons?domain=savyouthmentoring.org&sz=128', 'education', array['recurring', 'leadership role'], false, false, 16, 'United States', 'GA', 'Savannah', true, true, 'ongoing', false),
  -- GARDENING
  ('c1000000-0000-4000-8000-000000000037', null, 'Athens Land Trust', 'An Athens nonprofit protecting land and building community through affordable housing and community agriculture, including the West Broad Market Garden and a Young Urban Farmers program.', 'https://athenslandtrust.org', 'https://www.google.com/s2/favicons?domain=athenslandtrust.org&sz=128', 'gardening', array['outdoors', 'physical work', 'good for crews'], false, false, 14, 'United States', 'GA', 'Athens', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000038', null, 'The Metro Atlanta Urban Farm', 'A working urban farm in the College Park area that grows fresh produce to fight food insecurity and teaches sustainable agriculture, welcoming volunteers and groups for farm workdays.', 'https://themetroatlantaurbanfarm.org', 'https://www.google.com/s2/favicons?domain=themetroatlantaurbanfarm.org&sz=128', 'gardening', array['outdoors', 'physical work', 'family friendly'], false, false, 12, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000039', null, 'Concrete Jungle', 'An Atlanta and Athens nonprofit whose volunteers glean fruit from urban trees and harvest at partner farms, distributing fresh produce to soup kitchens and food pantries.', 'https://concrete-jungle.org', 'https://www.google.com/s2/favicons?domain=concrete-jungle.org&sz=128', 'gardening', array['outdoors', 'physical work', 'good for crews'], false, false, 12, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  -- COMMUNITY
  ('c1000000-0000-4000-8000-000000000040', null, 'North Fulton Community Charities', 'A Roswell nonprofit preventing homelessness and hunger in north Fulton with a food pantry, thrift store, and financial assistance, staffed largely by volunteers.', 'https://nfcchelp.org', 'https://www.google.com/s2/favicons?domain=nfcchelp.org&sz=128', 'community', array['recurring', 'good for crews', 'family friendly'], false, false, 13, 'United States', 'GA', 'Roswell', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000041', null, 'The Backpack Project', 'A student-run nonprofit that packs and hand-delivers backpacks of food, toiletries, and essentials to people experiencing homelessness, with chapters serving Athens, Atlanta, and Augusta.', 'https://www.thebackpackproject.ngo', 'https://www.google.com/s2/favicons?domain=www.thebackpackproject.ngo&sz=128', 'community', array['good for crews', 'counts for school hours', 'family friendly'], false, false, 14, 'United States', 'GA', 'Athens', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000042', null, 'Goodwill of North Georgia', 'A nonprofit that turns donated goods into job training and career services, helping tens of thousands of Georgians each year find work through its career centers.', 'https://goodwillng.org', 'https://www.google.com/s2/favicons?domain=goodwillng.org&sz=128', 'community', array['recurring', 'good for crews'], false, false, 16, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000043', null, 'Hands On Atlanta', 'A volunteer hub that matches individuals, families, and groups with hundreds of service projects at nonprofits and schools across metro Atlanta, making it easy to find a first project.', 'https://www.handsonatlanta.org', 'https://www.google.com/s2/favicons?domain=www.handsonatlanta.org&sz=128', 'community', array['good for crews', 'family friendly', 'recurring'], false, false, 13, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  -- MEDICINE
  ('c1000000-0000-4000-8000-000000000044', null, 'Ronald McDonald House Charities of Atlanta', 'A nonprofit providing a home away from home for families whose children are being treated at Atlanta hospitals, with volunteer roles cooking meals and welcoming families.', 'https://ronaldmcdonaldhouseatl.org', 'https://www.google.com/s2/favicons?domain=ronaldmcdonaldhouseatl.org&sz=128', 'medicine', array['recurring', 'family friendly', 'good for crews'], false, false, 13, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000045', null, 'Ronald McDonald House Charities of Central Georgia', 'The Macon-based Ronald McDonald House supporting families of hospitalized children in central Georgia, relying on volunteers for meals, housekeeping, and front-desk help.', 'https://www.rmhccga.org', 'https://www.google.com/s2/favicons?domain=www.rmhccga.org&sz=128', 'medicine', array['recurring', 'good for crews'], false, false, 16, 'United States', 'GA', 'Macon', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000046', null, 'Shepherd Center', 'A nationally ranked Atlanta hospital specializing in spinal cord and brain injury rehabilitation, with a large volunteer program supporting patients, families, and recreation therapy.', 'https://www.shepherd.org', 'https://www.google.com/s2/favicons?domain=www.shepherd.org&sz=128', 'medicine', array['recurring', 'counts for school hours'], false, false, 16, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  -- SPORTS
  ('c1000000-0000-4000-8000-000000000047', null, 'BlazeSports America', 'An Atlanta-based nonprofit and legacy of the 1996 Paralympic Games that provides adaptive sports and recreation for children and adults with physical disabilities.', 'https://blazesports.org', 'https://www.google.com/s2/favicons?domain=blazesports.org&sz=128', 'sports', array['recurring', 'leadership role'], false, false, 14, 'United States', 'GA', 'Decatur', true, true, 'both', false),
  ('c1000000-0000-4000-8000-000000000048', null, 'Soccer in the Streets', 'An Atlanta nonprofit using soccer to develop youth in under-resourced neighborhoods, famous for its StationSoccer fields built at MARTA transit stations.', 'https://www.soccerstreets.org', 'https://www.google.com/s2/favicons?domain=www.soccerstreets.org&sz=128', 'sports', array['recurring', 'leadership role'], false, false, 16, 'United States', 'GA', 'Atlanta', true, true, 'both', false),
  -- VETERANS
  ('c1000000-0000-4000-8000-000000000049', null, 'Middle Georgia Honor Flight', 'A nonprofit that flies World War II, Korea, and Vietnam-era veterans to Washington, D.C. at no cost to visit their memorials, pairing each veteran with a volunteer Guardian.', 'https://www.middlegahonorflight.org', 'https://www.google.com/s2/favicons?domain=www.middlegahonorflight.org&sz=128', 'veterans', array['leadership role', 'good for crews'], false, false, 16, 'United States', 'GA', 'Warner Robins', true, true, 'one-time', false),
  ('c1000000-0000-4000-8000-000000000050', null, 'Coastal Georgia Honor Flight', 'A Savannah-area nonprofit honoring coastal Georgia veterans with all-expenses-paid trips to see their memorials in Washington, D.C., supported by volunteers and Guardians.', 'https://coastalgeorgiahonorflight.org', 'https://www.google.com/s2/favicons?domain=coastalgeorgiahonorflight.org&sz=128', 'veterans', array['leadership role', 'good for crews'], false, false, 16, 'United States', 'GA', 'Savannah', true, true, 'one-time', false)
on conflict (id) do nothing;

insert into public.opportunities
  (id, org_id, title, category, description, tags, min_age, remote, is_online, is_ongoing,
   hours_estimate, signup_link, external_url, starts_at, city, state)
values
  -- NOTE: opportunity for the removed 'Atlanta Community Food Bank' (was c2...001) removed too.
  ('c2000000-0000-4000-8000-000000000002', 'c1000000-0000-4000-8000-000000000002', 'Drive a Food Rescue Route', 'food', 'Volunteers use their own vehicle to pick up surplus food from a grocer or restaurant and deliver it to a nearby agency that feeds people in need, usually a route of about an hour. Younger volunteers can ride along with a driving adult, so it works as a family activity. It is one of the most flexible ways to fight both hunger and food waste on your own schedule.', array['good for crews', 'recurring'], 14, false, false, true, '1-2 hrs / route', 'https://secondhelpingsatlanta.org/volunteer/', 'https://secondhelpingsatlanta.org/volunteer/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000003', 'c1000000-0000-4000-8000-000000000003', 'Help Cook or Deliver Meals for the Homebound', 'food', 'Volunteers help prepare medically tailored meals in the kitchen or deliver them to seniors and neighbors managing serious illness across metro Atlanta. Kitchen shifts are great for groups, while delivery routes let you check in one-on-one with the people you serve. Both roles have a real, immediate impact on someone''s day.', array['recurring', 'good for crews'], 13, false, false, true, '2-3 hrs', 'https://www.openhandatlanta.org/', 'https://www.openhandatlanta.org/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000004', 'c1000000-0000-4000-8000-000000000004', 'Sort Donations for the CSRA', 'food', 'Volunteers sort and box donated food and produce at Golden Harvest so it can move out to pantries across the Augusta region, and some shifts help at the Master''s Table community kitchen. It is steady, hands-on work that is easy to do with a crew or a class. Groups should reserve a shift in advance.', array['good for crews', 'family friendly'], 12, false, false, true, '2-3 hrs', 'https://www.goldenharvest.org/', 'https://www.goldenharvest.org/', '2026-01-01T00:00:00Z', 'Augusta', 'GA'),
  ('c2000000-0000-4000-8000-000000000005', 'c1000000-0000-4000-8000-000000000005', 'Pack Groceries for the Chattahoochee Valley', 'food', 'Volunteers help receive, sort, and repackage donated groceries and fresh produce at Feeding the Valley for distribution to partner pantries across west Georgia. Expect some standing and light lifting, which makes it a good pick if you want active work. It is a straightforward way for a group to make a big dent in local hunger in a couple of hours.', array['good for crews', 'physical work'], 12, false, false, true, '2-3 hrs', 'https://feedingthevalley.org/', 'https://feedingthevalley.org/', '2026-01-01T00:00:00Z', 'Columbus', 'GA'),
  ('c2000000-0000-4000-8000-000000000006', 'c1000000-0000-4000-8000-000000000006', 'Volunteer at the North Georgia Food Bank', 'food', 'Volunteers sort donations, pack food boxes, and help in the community garden at Georgia Mountain Food Bank in Gainesville, supporting families across five north Georgia counties. Roles fit a range of ages and abilities, so families and youth groups are welcome. Check the site for current shift times and to sign up.', array['good for crews', 'family friendly'], 12, false, false, true, '2-3 hrs', 'https://www.gamountainfoodbank.org/', 'https://www.gamountainfoodbank.org/', '2026-01-01T00:00:00Z', 'Gainesville', 'GA'),
  ('c2000000-0000-4000-8000-000000000007', 'c1000000-0000-4000-8000-000000000007', 'Pack Groceries with a Food Co-op', 'food', 'Volunteers join members to pack and hand out around 40,000 pounds of groceries a month at Urban Recipe, where neighbors shop with dignity instead of standing in a pantry line. You will work shoulder to shoulder with the very community you are serving. It is a warm, people-first way to help.', array['recurring', 'good for crews'], 12, false, false, true, '2-3 hrs', 'https://urbanrecipe.org/', 'https://urbanrecipe.org/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000008', 'c1000000-0000-4000-8000-000000000008', 'Care for Shelter Animals', 'animals', 'Volunteers help socialize dogs and cats, assist at adoption events, and support daily shelter operations at the Atlanta Humane Society. Most hands-on animal roles ask volunteers to be at least 16, and training is provided before you start. It is a great fit if you love animals and want a regular, recurring role.', array['recurring'], 16, false, false, true, '2-3 hrs', 'https://atlantahumane.org/', 'https://atlantahumane.org/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  -- NOTE: opportunity for the removed 'LifeLine Animal Project' (was c2...009) removed too.
  ('c2000000-0000-4000-8000-000000000010', 'c1000000-0000-4000-8000-000000000010', 'Socialize Cats and Puppies at Furkids', 'animals', 'Volunteers help socialize animals and keep the shelter running at Georgia''s largest no-kill rescue, and there are youth roles: kids under 16 can help in the cat shelter with a parent, and teens 13 to 18 can join puppy socialization with a parent. It is one of the more family-friendly animal options in the metro area.', array['family friendly', 'recurring'], 13, false, false, true, '2-3 hrs', 'https://furkids.org/volunteer', 'https://furkids.org/volunteer', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000011', 'c1000000-0000-4000-8000-000000000011', 'Volunteer at a No-Kill Shelter in Decatur', 'animals', 'Volunteers help with animal care, adoptions, and events at PAWS Atlanta in Decatur. On-site volunteers need to be at least 18 whether you come alone or with a group, though shelter tours are open to all ages. If you are 18 or older and want steady time with shelter animals, this is a solid pick.', array['recurring'], 18, false, false, true, '2-3 hrs', 'https://www.pawsatlanta.org/volunteer-overview', 'https://www.pawsatlanta.org/volunteer-overview', '2026-01-01T00:00:00Z', 'Decatur', 'GA'),
  ('c2000000-0000-4000-8000-000000000012', 'c1000000-0000-4000-8000-000000000012', 'Help Animals in the Savannah Area', 'animals', 'Volunteers pitch in on hands-on animal care, community programs, and special events at the Humane Society for Greater Savannah, with roles to fit different ages and interests. It is a welcoming place to get started with animal-welfare work on the coast. Reach out through the site to find a role that matches your availability.', array['recurring', 'family friendly'], 14, false, false, true, '2-3 hrs', 'https://www.humanesocietysav.org/volunteer', 'https://www.humanesocietysav.org/volunteer', '2026-01-01T00:00:00Z', 'Savannah', 'GA'),
  ('c2000000-0000-4000-8000-000000000013', 'c1000000-0000-4000-8000-000000000013', 'Help Rehabilitate Native Wildlife', 'animals', 'Volunteers help feed and care for injured and orphaned native animals, prepare diets, and maintain habitats at the AWARE Wildlife Center near Arabia Mountain. Training is provided, and it is a rare chance to work directly with Georgia wildlife rather than pets. Expect hands-on, sometimes messy work outdoors.', array['outdoors', 'recurring'], 16, false, false, true, '3-4 hrs', 'https://awarewildlife.org/', 'https://awarewildlife.org/', '2026-01-01T00:00:00Z', 'Lithonia', 'GA'),
  ('c2000000-0000-4000-8000-000000000014', 'c1000000-0000-4000-8000-000000000014', 'Foster or Support Rescue Pets', 'animals', 'Volunteers help at adoption events, support foster homes, and assist with the day-to-day work of a foster-based rescue in the Savannah area. Teens can volunteer with parental permission through the CPR Teens program, and fostering is a great option if your family can host a pet short-term. Start with the volunteer application on their site.', array['recurring', 'family friendly'], 14, false, false, true, '2-3 hrs', 'https://coastalpetrescue.org/get-involved/volunteer-application', 'https://coastalpetrescue.org/get-involved/volunteer-application', '2026-01-01T00:00:00Z', 'Savannah', 'GA'),
  ('c2000000-0000-4000-8000-000000000015', 'c1000000-0000-4000-8000-000000000015', 'Support Young Musicians at AMP', 'music', 'Volunteers help behind the scenes at Atlanta Music Project - assisting at rehearsals and concerts, helping with instruments, and supporting students in the program. It is a great fit if you play an instrument yourself or just want to help young musicians thrive. Roles range from one-time event help to ongoing support.', array['recurring', 'creative work'], 14, false, false, true, '2-3 hrs', 'https://atlantamusicproject.org/support/volunteer-at-amp/', 'https://atlantamusicproject.org/support/volunteer-at-amp/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000016', 'c1000000-0000-4000-8000-000000000016', 'Help Bring Music to the Community', 'music', 'Volunteers help paint and place street pianos, staff festival events, and support arts programs Pianos for Peace brings to schools, hospitals, and senior homes. It is a colorful, creative way to volunteer, and group projects are welcome. Watch the site for the annual festival, when the most help is needed.', array['creative work', 'good for crews'], 13, false, false, true, '2-4 hrs', 'https://www.pianosforpeace.org/', 'https://www.pianosforpeace.org/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000017', 'c1000000-0000-4000-8000-000000000017', 'Mentor a Student Musician', 'music', 'Volunteers serve as mentors, guest artists, or general helpers with Henry For Music, which gifts free instruments and lessons to students who need them most. If you play an instrument, you can share that skill directly; if not, there is still plenty of behind-the-scenes help needed. It is a meaningful role for anyone who believes every kid deserves access to music.', array['creative work', 'recurring'], 14, false, false, true, '1-2 hrs / week', 'https://henryformusic.org/volunteers', 'https://henryformusic.org/volunteers', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000018', 'c1000000-0000-4000-8000-000000000018', 'Volunteer Your Tech Skills for Good', 'tech', 'Volunteers with an interest in technology help at TechBridge events and support its mission of bringing tech to other nonprofits, with occasional mentoring roles in its career-training program. It is a strong pick if you are into computers, coding, or IT and want to see how those skills fight poverty. Check the events page for current opportunities.', array['recurring', 'leadership role'], 16, false, false, true, 'Varies', 'https://techbridge.org/events/volunteer/', 'https://techbridge.org/events/volunteer/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000019', 'c1000000-0000-4000-8000-000000000019', 'Mentor Youth in STEM and Esports', 'tech', 'Volunteers help teach and mentor students in free coding, STEM, and esports programs Bridge2Tech runs for underserved Georgia youth. If you know your way around a computer or a game, you can pass those skills on to a younger student. It is a fun, modern way to earn service hours while sharing something you already enjoy.', array['recurring', 'leadership role', 'counts for school hours'], 13, false, false, true, '2-3 hrs', 'https://www.bridge2tech.org/', 'https://www.bridge2tech.org/', '2026-01-01T00:00:00Z', 'Roswell', 'GA'),
  ('c2000000-0000-4000-8000-000000000020', 'c1000000-0000-4000-8000-000000000020', 'Build Homes with Atlanta Habitat', 'faith', 'Volunteers work alongside future homeowners on a build site, doing everything from painting and landscaping to construction, with no experience needed and tools and guidance provided. Build-day volunteers must be at least 16, and it is one of the best group projects in the city. You can also help at the ReStore if you prefer indoor work.', array['good for crews', 'physical work', 'outdoors'], 16, false, false, true, 'Full day', 'https://atlantahabitat.org/volunteer/', 'https://atlantahabitat.org/volunteer/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000021', 'c1000000-0000-4000-8000-000000000021', 'Build and Repair Homes in Augusta', 'faith', 'Volunteers help build and rehab affordable homes across the Augusta and CSRA region, and both skilled and unskilled hands are welcome. Build-site roles generally ask volunteers to be at least 16. It is rewarding, physical, team-based work that leaves something lasting behind.', array['good for crews', 'physical work', 'outdoors'], 16, false, false, true, 'Full day', 'https://augustahabitat.org/volunteer/', 'https://augustahabitat.org/volunteer/', '2026-01-01T00:00:00Z', 'Augusta', 'GA'),
  ('c2000000-0000-4000-8000-000000000022', 'c1000000-0000-4000-8000-000000000022', 'Tutor or Mentor Through Catholic Charities', 'faith', 'Volunteers help with after-school tutoring, English-language classes, youth mentorship, and welcoming newly resettled refugee families in the Atlanta area. Opportunities range from one-time projects to regular weekly commitments, and volunteers of all faiths are welcome. It is a good option if you want to support new arrivals building a life here.', array['recurring', 'counts for school hours'], 14, false, false, true, '1-2 hrs / week', 'https://catholiccharitiesatlanta.org/get-involved/volunteer/', 'https://catholiccharitiesatlanta.org/get-involved/volunteer/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000023', 'c1000000-0000-4000-8000-000000000023', 'Serve Neighbors in Need with MUST', 'faith', 'Volunteers prepare and serve meals, sort donations, and help at MUST Ministries'' food pantry and shelter serving Cobb, Cherokee, and nearby counties, plus a big summer lunch program for kids. There are roles for individuals, families, and large groups. It is a welcoming place to serve regardless of your background.', array['good for crews', 'family friendly', 'recurring'], 13, false, false, true, '2-3 hrs', 'https://www.mustministries.org/', 'https://www.mustministries.org/', '2026-01-01T00:00:00Z', 'Marietta', 'GA'),
  ('c2000000-0000-4000-8000-000000000024', 'c1000000-0000-4000-8000-000000000024', 'Train as a Red Cross Disaster Volunteer', 'disaster', 'With just a few hours of training, volunteers join a team ready to bring food, shelter, and comfort when a home fire, hurricane, or other disaster strikes, either here in Georgia or on deployment elsewhere. Most disaster roles ask volunteers to be at least 16. It is a serious commitment with real responsibility and real impact.', array['recurring', 'leadership role'], 16, false, false, true, 'Varies', 'https://www.redcross.org/local/georgia.html', 'https://www.redcross.org/local/georgia.html', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000025', 'c1000000-0000-4000-8000-000000000025', 'Join a Savannah River Cleanup', 'environment', 'Volunteers join organized cleanups along the Savannah River in Augusta, Savannah, and points between, pulling trash and debris from the water and banks; gloves and bags are provided. Kids up to 16 are welcome with an adult, and anyone under 18 needs a guardian to sign a waiver. It is an easy, high-impact day outdoors for a group.', array['outdoors', 'physical work', 'good for crews'], 12, false, false, true, '2-4 hrs', 'https://www.savannahriverkeeper.org/volunteer.html', 'https://www.savannahriverkeeper.org/volunteer.html', '2026-01-01T00:00:00Z', 'Augusta', 'GA'),
  ('c2000000-0000-4000-8000-000000000026', 'c1000000-0000-4000-8000-000000000026', 'Test Water and Clean Up Coastal Waterways', 'environment', 'Volunteers help with litter cleanups and water-quality testing along the Ogeechee and coastal waterways, including the Protect the Vernon project. It is a great way to learn real environmental science while doing hands-on conservation. Cleanups are family-friendly with adult supervision.', array['outdoors', 'physical work', 'good for crews'], 12, false, false, true, '2-3 hrs', 'https://www.ogeecheeriverkeeper.org/volunteer/', 'https://www.ogeecheeriverkeeper.org/volunteer/', '2026-01-01T00:00:00Z', 'Savannah', 'GA'),
  ('c2000000-0000-4000-8000-000000000027', 'c1000000-0000-4000-8000-000000000027', 'Protect Atlanta''s Drinking Water', 'environment', 'Volunteers join river cleanups and water-monitoring events with Chattahoochee Riverkeeper, which protects the river that supplies most of metro Atlanta''s drinking water. Projects run throughout the year and range from single cleanup days to ongoing monitoring. It is a concrete way to protect something every Atlantan depends on.', array['outdoors', 'physical work', 'good for crews'], 12, false, false, true, '2-4 hrs', 'https://chattahoochee.org/', 'https://chattahoochee.org/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000028', 'c1000000-0000-4000-8000-000000000028', 'Help at the Chattahoochee Nature Center', 'environment', 'Volunteers assist with wildlife care, garden and grounds work, education programs, and events across the nature center''s 127 acres in Roswell. There are roles for teens and adults, and it is a beautiful outdoor setting to give your time. Recurring volunteers get to know the resident animals and the land.', array['outdoors', 'recurring', 'family friendly'], 12, false, false, true, '2-3 hrs', 'https://www.chattnaturecenter.org/', 'https://www.chattnaturecenter.org/', '2026-01-01T00:00:00Z', 'Roswell', 'GA'),
  ('c2000000-0000-4000-8000-000000000029', 'c1000000-0000-4000-8000-000000000029', 'Adopt and Monitor a Local Stream', 'environment', 'Volunteers get trained through Georgia Adopt-A-Stream to regularly test and monitor a nearby stream, river, or wetland, collecting data that helps protect the state''s waterways. It is a self-directed, recurring role you can do close to home, which makes it great for a school project or a small crew. Training and equipment guidance are provided.', array['outdoors', 'recurring', 'counts for school hours'], 12, false, false, true, '1-2 hrs / month', 'https://adoptastream.georgia.gov/', 'https://adoptastream.georgia.gov/', '2026-01-01T00:00:00Z', 'Georgia', 'GA'),
  ('c2000000-0000-4000-8000-000000000030', 'c1000000-0000-4000-8000-000000000030', 'Deliver Meals to Coastal Georgia Seniors', 'seniors', 'Volunteers deliver Meals on Wheels along a set route to homebound older adults across the Savannah area, spending a moment at each stop to say hello and make sure the senior is okay. A route usually takes about an hour and can become a regular weekly commitment. For many clients, that daily visit is the highlight of their day.', array['recurring'], 16, false, false, true, '1 hr / route', 'https://seniorcitizensinc.org/meals-on-wheels-of-coastal-georgia', 'https://seniorcitizensinc.org/meals-on-wheels-of-coastal-georgia', '2026-01-01T00:00:00Z', 'Savannah', 'GA'),
  ('c2000000-0000-4000-8000-000000000031', 'c1000000-0000-4000-8000-000000000031', 'Deliver Meals Around Macon', 'seniors', 'Volunteers deliver hot meals and a friendly check-in to homebound seniors around Macon and middle Georgia along a set route. It is a short, reliable way to help - most routes take about an hour - and it pairs well with a regular weekly schedule. Bring a smile; the visit matters as much as the meal.', array['recurring'], 16, false, false, true, '1 hr / route', 'https://www.mowmidga.org/', 'https://www.mowmidga.org/', '2026-01-01T00:00:00Z', 'Macon', 'GA'),
  ('c2000000-0000-4000-8000-000000000032', 'c1000000-0000-4000-8000-000000000032', 'Support Older Adults in Athens', 'seniors', 'Volunteers help deliver meals, assist with day programs and events, and work in the community garden at the Athens Community Council on Aging. Roles range from indoor companionship to outdoor garden work, so there is a good fit for most interests. It is a welcoming place to build a recurring relationship with older neighbors.', array['recurring', 'outdoors'], 14, false, false, true, '1-2 hrs', 'https://www.accaging.org/', 'https://www.accaging.org/', '2026-01-01T00:00:00Z', 'Athens', 'GA'),
  ('c2000000-0000-4000-8000-000000000033', 'c1000000-0000-4000-8000-000000000033', 'Be a Mentor, Reading Coach, or Lunch Buddy', 'education', 'Volunteers come into partner schools to mentor students, coach reading, or simply be a lunch buddy, helping kids stay on track and finish school. Roles happen during the school day and reward a consistent, recurring commitment. It is a great option if you want a real relationship with a student rather than a one-off project.', array['recurring', 'counts for school hours', 'leadership role'], 16, false, false, true, '1-2 hrs / week', 'https://www.cisatlanta.org/get-involved', 'https://www.cisatlanta.org/get-involved', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000034', 'c1000000-0000-4000-8000-000000000034', 'Help at a Summer Learning Program', 'education', 'Volunteers support Horizons Atlanta''s six-week summer program by reading with students, helping in the classroom, or joining as a mystery reader for a day. It is a fun, upbeat way to help close the summer learning gap for kids from under-resourced communities. Most opportunities run in the summer, so plan for June and July.', array['recurring', 'counts for school hours'], 14, false, false, true, '2-3 hrs', 'https://horizonsatlanta.org/about/volunteer-with-us/', 'https://horizonsatlanta.org/about/volunteer-with-us/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000035', 'c1000000-0000-4000-8000-000000000035', 'Teach a Junior Achievement Lesson', 'education', 'Volunteers lead hands-on JA lessons in a classroom, showing students how money, careers, and entrepreneurship work in real life, usually as a single day for an individual or a team. Volunteers need to be 18 or older and register on JA''s site first. It is a high-impact way to spend one day sharing what you know.', array['leadership role', 'counts for school hours'], 18, false, false, true, 'Half day', 'https://www.georgia.ja.org/volunteer', 'https://www.georgia.ja.org/volunteer', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000036', 'c1000000-0000-4000-8000-000000000036', 'Become a Youth Mentor in Savannah', 'education', 'The Savannah Youth Mentoring Hub makes it easy to find a vetted local mentoring organization and apply to become a mentor to a young person in the community. It is the right starting point if you want to mentor but are not sure which program to join. Because mentoring is an ongoing relationship, expect a real, sustained commitment.', array['recurring', 'leadership role'], 16, false, false, true, '1-2 hrs / week', 'https://savyouthmentoring.org/', 'https://savyouthmentoring.org/', '2026-01-01T00:00:00Z', 'Savannah', 'GA'),
  ('c2000000-0000-4000-8000-000000000037', 'c1000000-0000-4000-8000-000000000037', 'Work a Community Garden Day in Athens', 'gardening', 'Volunteers help plant, weed, and harvest at the West Broad Market Garden and other Athens Land Trust sites, growing fresh food for the community. It is hands-on outdoor work that is easy to do as a group and welcoming to first-timers. You will leave with dirt on your hands and a real sense of what it takes to grow food.', array['outdoors', 'physical work', 'good for crews'], 14, false, false, true, '2-3 hrs', 'https://athenslandtrust.org/our-work/comag/', 'https://athenslandtrust.org/our-work/comag/', '2026-01-01T00:00:00Z', 'Athens', 'GA'),
  ('c2000000-0000-4000-8000-000000000038', 'c1000000-0000-4000-8000-000000000038', 'Join a Farm Workday', 'gardening', 'Volunteers help plant, weed, harvest, and maintain the beds at the Metro Atlanta Urban Farm, which grows fresh produce to fight food insecurity near College Park. The farm welcomes volunteers of all ages and groups, so it works well for families. Expect real, satisfying outdoor work.', array['outdoors', 'physical work', 'family friendly'], 12, false, false, true, '2-3 hrs', 'https://themetroatlantaurbanfarm.org/volunteering-sponsorship/', 'https://themetroatlantaurbanfarm.org/volunteering-sponsorship/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000039', 'c1000000-0000-4000-8000-000000000039', 'Glean Fruit for Neighbors in Need', 'gardening', 'Volunteers meet up to pick fruit from urban trees or harvest at partner farms with Concrete Jungle, then help get the fresh produce to soup kitchens and food pantries. It is a fun, active, outdoors way to fight both food waste and hunger. Harvests happen regularly in both Atlanta and Athens.', array['outdoors', 'physical work', 'good for crews'], 12, false, false, true, '2-3 hrs', 'https://concrete-jungle.org/volunteer/', 'https://concrete-jungle.org/volunteer/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000040', 'c1000000-0000-4000-8000-000000000040', 'Help at the Pantry or Thrift Store', 'community', 'Volunteers stock and sort at the food pantry, help customers in the thrift store, and support families getting emergency assistance at North Fulton Community Charities in Roswell. There are roles for teens with a guardian and for groups. It is a friendly, well-organized place to give a few hours close to home.', array['recurring', 'good for crews', 'family friendly'], 13, false, false, true, '2-3 hrs', 'https://nfcchelp.org/', 'https://nfcchelp.org/', '2026-01-01T00:00:00Z', 'Roswell', 'GA'),
  ('c2000000-0000-4000-8000-000000000041', 'c1000000-0000-4000-8000-000000000041', 'Pack Backpacks for Neighbors Experiencing Homelessness', 'community', 'Volunteers help assemble backpacks of food, toiletries, and essentials and, at some events, hand them directly to people experiencing homelessness in Athens, Atlanta, or Augusta. Run by students, it is an especially good fit for teens and youth groups. Packing events are social and easy to jump into for a first project.', array['good for crews', 'counts for school hours', 'family friendly'], 14, false, false, true, '2-3 hrs', 'https://www.thebackpackproject.ngo/', 'https://www.thebackpackproject.ngo/', '2026-01-01T00:00:00Z', 'Athens', 'GA'),
  ('c2000000-0000-4000-8000-000000000042', 'c1000000-0000-4000-8000-000000000042', 'Support Job Seekers at Goodwill', 'community', 'Volunteers help at Goodwill of North Georgia career centers and donation sites, supporting the job training and placement services that help thousands of Georgians find work each year. Roles vary from sorting donations to helping people practice for interviews. It is a good pick if you want your time to support workforce and economic opportunity.', array['recurring', 'good for crews'], 16, false, false, true, '2-3 hrs', 'https://goodwillng.org/', 'https://goodwillng.org/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000043', 'c1000000-0000-4000-8000-000000000043', 'Find Your First Project with Hands On Atlanta', 'community', 'Hands On Atlanta lists hundreds of vetted service projects at nonprofits and schools across the metro area, so you can browse by cause, date, and location and sign up in minutes. It is the easiest way to try several different kinds of volunteering before committing to one. Great for individuals, families, and groups alike.', array['good for crews', 'family friendly', 'recurring'], 13, false, false, true, 'Varies', 'https://www.handsonatlanta.org/', 'https://www.handsonatlanta.org/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000044', 'c1000000-0000-4000-8000-000000000044', 'Cook a Meal for Families at the House', 'medicine', 'Volunteers prepare and serve a meal or help welcome families staying at the Ronald McDonald House while their children are treated at Atlanta hospitals. Cooking a meal is a favorite group project, and there are family-friendly roles for teens with an adult. A home-cooked dinner can be a huge comfort to a family having a hard week.', array['recurring', 'family friendly', 'good for crews'], 13, false, false, true, '2-3 hrs', 'https://ronaldmcdonaldhouseatl.org/get-involved/', 'https://ronaldmcdonaldhouseatl.org/get-involved/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000045', 'c1000000-0000-4000-8000-000000000045', 'Support Families in Macon', 'medicine', 'Volunteers help with meals, light housekeeping, and front-desk welcome at the Ronald McDonald House of Central Georgia, supporting families whose children are hospitalized in the Macon area. Roles are steady and rewarding, and groups can sign up to cook a meal together. It is a direct way to comfort families during a stressful time.', array['recurring', 'good for crews'], 16, false, false, true, '2-3 hrs', 'https://www.rmhccga.org/volunteer.php', 'https://www.rmhccga.org/volunteer.php', '2026-01-01T00:00:00Z', 'Macon', 'GA'),
  ('c2000000-0000-4000-8000-000000000046', 'c1000000-0000-4000-8000-000000000046', 'Volunteer at Shepherd Center', 'medicine', 'Volunteers support patients and families at Shepherd Center, one of the top spinal cord and brain injury rehabilitation hospitals in the country, helping with recreation therapy, wayfinding, and patient activities. It is an excellent fit if you are considering a career in health or rehabilitation. Roles are ongoing, and training is provided.', array['recurring', 'counts for school hours'], 16, false, false, true, '2-3 hrs / week', 'https://www.shepherd.org/', 'https://www.shepherd.org/', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000047', 'c1000000-0000-4000-8000-000000000047', 'Help Run Adaptive Sports Programs', 'sports', 'Volunteers assist coaches and athletes at BlazeSports adaptive sports clinics and events for children and adults with physical disabilities, from wheelchair basketball to swimming. No sports expertise is required, just enthusiasm and a willingness to help. It is a joyful, high-energy way to volunteer.', array['recurring', 'leadership role'], 14, false, false, true, '2-4 hrs', 'https://blazesports.org/', 'https://blazesports.org/', '2026-01-01T00:00:00Z', 'Decatur', 'GA'),
  ('c2000000-0000-4000-8000-000000000048', 'c1000000-0000-4000-8000-000000000048', 'Coach Youth Soccer at a MARTA Station', 'sports', 'Volunteers help coach and mentor young players at Soccer in the Streets programs, including the StationSoccer fields built right at MARTA transit stops. If you love soccer, you can pass that on to kids in under-resourced neighborhoods. Roles reward a regular, recurring commitment through the season.', array['recurring', 'leadership role'], 16, false, false, true, '2-3 hrs / week', 'https://www.soccerstreets.org/volunteer', 'https://www.soccerstreets.org/volunteer', '2026-01-01T00:00:00Z', 'Atlanta', 'GA'),
  ('c2000000-0000-4000-8000-000000000049', 'c1000000-0000-4000-8000-000000000049', 'Support a Veterans Honor Flight', 'veterans', 'Volunteers help plan and staff Honor Flight trips that take middle Georgia veterans to see their memorials in Washington, D.C., from fundraising and events to serving as a Guardian who accompanies a veteran (Guardians must be adults). It is a deeply moving way to thank the veterans in your community. Check the site for the next flight and how to help.', array['leadership role', 'good for crews'], 16, false, false, true, 'Varies', 'https://www.middlegahonorflight.org/volunteers', 'https://www.middlegahonorflight.org/volunteers', '2026-01-01T00:00:00Z', 'Warner Robins', 'GA'),
  ('c2000000-0000-4000-8000-000000000050', 'c1000000-0000-4000-8000-000000000050', 'Honor Coastal Georgia Veterans', 'veterans', 'Volunteers support Coastal Georgia Honor Flight through events, fundraising, and welcome-home celebrations for veterans returning from their trip to the memorials in Washington, D.C. It is a great way to show gratitude to local veterans, and welcome-home events are open to families and groups. Reach out through the site to get involved.', array['leadership role', 'good for crews'], 16, false, false, true, 'Varies', 'https://coastalgeorgiahonorflight.org/', 'https://coastalgeorgiahonorflight.org/', '2026-01-01T00:00:00Z', 'Savannah', 'GA')
on conflict (id) do nothing;
